-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer17_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
    layer17_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_empty_n : IN STD_LOGIC;
    layer17_out_read : OUT STD_LOGIC;
    layer18_out_TDATA : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer18_out_TVALID : OUT STD_LOGIC;
    layer18_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000100";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_121 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100001";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_135 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110101";
    constant ap_const_lv32_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer17_out_blk_n : STD_LOGIC;
    signal layer18_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_fu_209_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_reg_602 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_1_reg_607 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_2_reg_612 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_3_reg_617 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_4_reg_622 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_5_reg_627 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_6_reg_632 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_7_reg_637 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_8_reg_642 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_9_reg_647 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_31_reg_652 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_10_reg_657 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_11_reg_662 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_12_reg_667 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_13_reg_672 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_14_reg_677 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_15_reg_682 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_16_reg_687 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_17_reg_692 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_18_reg_697 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_19_reg_702 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_20_reg_707 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_21_reg_712 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_22_reg_717 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_23_reg_722 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_24_reg_727 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_25_reg_732 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_26_reg_737 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_27_reg_742 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_28_reg_747 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_29_reg_752 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_30_reg_757 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call35 : BOOLEAN;
    signal layer17_out_read_local : STD_LOGIC;
    signal tmp_fu_575_p10 : STD_LOGIC_VECTOR (73 downto 0);
    signal regslice_both_layer18_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal layer18_out_TDATA_int_regslice : STD_LOGIC_VECTOR (79 downto 0);
    signal layer18_out_TVALID_int_regslice : STD_LOGIC;
    signal layer18_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer18_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171 : component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start,
        ap_done => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done,
        ap_idle => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_idle,
        ap_ready => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready,
        data_0_val => data_reg_602,
        data_1_val => data_1_reg_607,
        data_2_val => data_2_reg_612,
        data_3_val => data_3_reg_617,
        data_4_val => data_4_reg_622,
        data_5_val => data_5_reg_627,
        data_6_val => data_6_reg_632,
        data_7_val => data_7_reg_637,
        data_8_val => data_8_reg_642,
        data_9_val => data_9_reg_647,
        data_10_val => data_31_reg_652,
        data_11_val => data_10_reg_657,
        data_12_val => data_11_reg_662,
        data_13_val => data_12_reg_667,
        data_14_val => data_13_reg_672,
        data_15_val => data_14_reg_677,
        data_16_val => data_15_reg_682,
        data_17_val => data_16_reg_687,
        data_18_val => data_17_reg_692,
        data_19_val => data_18_reg_697,
        data_20_val => data_19_reg_702,
        data_21_val => data_20_reg_707,
        data_22_val => data_21_reg_712,
        data_23_val => data_22_reg_717,
        data_24_val => data_23_reg_722,
        data_25_val => data_24_reg_727,
        data_26_val => data_25_reg_732,
        data_27_val => data_26_reg_737,
        data_28_val => data_27_reg_742,
        data_29_val => data_28_reg_747,
        data_30_val => data_29_reg_752,
        data_31_val => data_30_reg_757,
        ap_return_0 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4);

    regslice_both_layer18_out_U : component myproject_regslice_both
    generic map (
        DataWidth => 80)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer18_out_TDATA_int_regslice,
        vld_in => layer18_out_TVALID_int_regslice,
        ack_in => layer18_out_TREADY_int_regslice,
        data_out => layer18_out_TDATA,
        vld_out => regslice_both_layer18_out_U_vld_out,
        ack_out => layer18_out_TREADY,
        apdone_blk => regslice_both_layer18_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call35) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_10_reg_657 <= layer17_out_dout(119 downto 110);
                data_11_reg_662 <= layer17_out_dout(129 downto 120);
                data_12_reg_667 <= layer17_out_dout(139 downto 130);
                data_13_reg_672 <= layer17_out_dout(149 downto 140);
                data_14_reg_677 <= layer17_out_dout(159 downto 150);
                data_15_reg_682 <= layer17_out_dout(169 downto 160);
                data_16_reg_687 <= layer17_out_dout(179 downto 170);
                data_17_reg_692 <= layer17_out_dout(189 downto 180);
                data_18_reg_697 <= layer17_out_dout(199 downto 190);
                data_19_reg_702 <= layer17_out_dout(209 downto 200);
                data_1_reg_607 <= layer17_out_dout(19 downto 10);
                data_20_reg_707 <= layer17_out_dout(219 downto 210);
                data_21_reg_712 <= layer17_out_dout(229 downto 220);
                data_22_reg_717 <= layer17_out_dout(239 downto 230);
                data_23_reg_722 <= layer17_out_dout(249 downto 240);
                data_24_reg_727 <= layer17_out_dout(259 downto 250);
                data_25_reg_732 <= layer17_out_dout(269 downto 260);
                data_26_reg_737 <= layer17_out_dout(279 downto 270);
                data_27_reg_742 <= layer17_out_dout(289 downto 280);
                data_28_reg_747 <= layer17_out_dout(299 downto 290);
                data_29_reg_752 <= layer17_out_dout(309 downto 300);
                data_2_reg_612 <= layer17_out_dout(29 downto 20);
                data_30_reg_757 <= layer17_out_dout(319 downto 310);
                data_31_reg_652 <= layer17_out_dout(109 downto 100);
                data_3_reg_617 <= layer17_out_dout(39 downto 30);
                data_4_reg_622 <= layer17_out_dout(49 downto 40);
                data_5_reg_627 <= layer17_out_dout(59 downto 50);
                data_6_reg_632 <= layer17_out_dout(69 downto 60);
                data_7_reg_637 <= layer17_out_dout(79 downto 70);
                data_8_reg_642 <= layer17_out_dout(89 downto 80);
                data_9_reg_647 <= layer17_out_dout(99 downto 90);
                data_reg_602 <= data_fu_209_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_block_state1, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done, ap_block_state3, layer18_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done, layer18_out_TREADY_int_regslice)
    begin
        if (((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3, layer18_out_TREADY_int_regslice)
    begin
        if (((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3))) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, layer17_out_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (layer17_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call35_assign_proc : process(ap_start, ap_done_reg, layer17_out_empty_n)
    begin
                ap_block_state1_ignore_call35 <= ((ap_start = ap_const_logic_0) or (layer17_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(regslice_both_layer18_out_U_apdone_blk, layer18_out_TREADY_int_regslice)
    begin
                ap_block_state3 <= ((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_layer18_out_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3, layer18_out_TREADY_int_regslice)
    begin
        if ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3, layer18_out_TREADY_int_regslice)
    begin
        if ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    data_fu_209_p1 <= layer17_out_dout(10 - 1 downto 0);
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg;

    layer17_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer17_out_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer17_out_blk_n <= layer17_out_empty_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer17_out_read <= layer17_out_read_local;

    layer17_out_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer17_out_read_local <= ap_const_logic_1;
        else 
            layer17_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer18_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, layer18_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer18_out_TDATA_blk_n <= layer18_out_TREADY_int_regslice;
        else 
            layer18_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer18_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_575_p10),80));
    layer18_out_TVALID <= regslice_both_layer18_out_U_vld_out;

    layer18_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done, layer18_out_TREADY_int_regslice)
    begin
        if ((not(((layer18_out_TREADY_int_regslice = ap_const_logic_0) or (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer18_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer18_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_575_p10 <= ((((((((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4 & ap_const_lv6_0) & grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3) & ap_const_lv6_0) & grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2) & ap_const_lv6_0) & grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1) & ap_const_lv6_0) & grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0);
end behav;
