-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer2_out_dout : IN STD_LOGIC_VECTOR (79 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_empty_n : IN STD_LOGIC;
    layer2_out_read : OUT STD_LOGIC;
    layer4_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer4_out_full_n : IN STD_LOGIC;
    layer4_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer2_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer4_out_blk_n : STD_LOGIC;
    signal out_data_1_fu_265_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_1_reg_440 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal out_data_3_fu_279_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_3_reg_445 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_5_fu_293_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_5_reg_450 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_7_fu_307_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_7_reg_455 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_fu_321_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_reg_460 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_1_fu_335_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_1_reg_465 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_2_fu_349_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_2_reg_470 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_3_fu_363_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_3_reg_475 : STD_LOGIC_VECTOR (8 downto 0);
    signal i1_fu_86 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal i_fu_371_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (9 downto 0);
    signal layer2_out_read_local : STD_LOGIC;
    signal zext_ln57_fu_428_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal layer4_out_write_local : STD_LOGIC;
    signal out_data_fu_111_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_11_fu_115_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_2_fu_119_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_1_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_1_fu_129_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_4_fu_139_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_2_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_2_fu_149_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_6_fu_159_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_3_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_3_fu_169_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_4_fu_179_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_4_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_8_fu_189_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_5_fu_199_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_5_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_9_fu_209_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_6_fu_219_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_6_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_s_fu_229_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_7_fu_239_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_7_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_249_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln51_2_fu_406_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_1_fu_403_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_fu_400_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_3_fu_397_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_2_fu_394_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_1_fu_391_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_fu_388_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln57_s_fu_409_p9 : STD_LOGIC_VECTOR (78 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_123 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i1_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_123)) then
                i1_fu_86 <= i_fu_371_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_data_1_reg_440 <= out_data_1_fu_265_p3;
                out_data_3_reg_445 <= out_data_3_fu_279_p3;
                out_data_5_reg_450 <= out_data_5_fu_293_p3;
                out_data_7_reg_455 <= out_data_7_fu_307_p3;
                select_ln51_1_reg_465 <= select_ln51_1_fu_335_p3;
                select_ln51_2_reg_470 <= select_ln51_2_fu_349_p3;
                select_ln51_3_reg_475 <= select_ln51_3_fu_363_p3;
                select_ln51_reg_460 <= select_ln51_fu_321_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(layer2_out_empty_n, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (layer2_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer4_out_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer4_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_123_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_123 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_377_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_377_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i1_fu_86, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_86;
        end if; 
    end process;

    i_fu_371_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv10_1));
    icmp_ln41_fu_377_p2 <= "1" when (ap_sig_allocacmp_i1_load = ap_const_lv10_3FF) else "0";
    icmp_ln51_1_fu_273_p2 <= "1" when (signed(out_data_2_fu_119_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_2_fu_287_p2 <= "1" when (signed(out_data_4_fu_139_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_3_fu_301_p2 <= "1" when (signed(out_data_6_fu_159_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_4_fu_315_p2 <= "1" when (signed(trunc_ln44_4_fu_179_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_5_fu_329_p2 <= "1" when (signed(trunc_ln44_5_fu_199_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_6_fu_343_p2 <= "1" when (signed(trunc_ln44_6_fu_219_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_7_fu_357_p2 <= "1" when (signed(trunc_ln44_7_fu_239_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_fu_259_p2 <= "1" when (signed(out_data_fu_111_p1) > signed(ap_const_lv10_0)) else "0";

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, layer2_out_empty_n, ap_done_reg, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_empty_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer2_out_read <= layer2_out_read_local;

    layer2_out_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_read_local <= ap_const_logic_1;
        else 
            layer2_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer4_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_blk_n <= layer4_out_full_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4_out_din <= zext_ln57_fu_428_p1;
    layer4_out_write <= layer4_out_write_local;

    layer4_out_write_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_write_local <= ap_const_logic_1;
        else 
            layer4_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_409_p9 <= (((((((select_ln51_3_reg_475 & zext_ln51_2_fu_406_p1) & zext_ln51_1_fu_403_p1) & zext_ln51_fu_400_p1) & zext_ln45_3_fu_397_p1) & zext_ln45_2_fu_394_p1) & zext_ln45_1_fu_391_p1) & zext_ln45_fu_388_p1);
    out_data_1_fu_265_p3 <= 
        trunc_ln44_11_fu_115_p1 when (icmp_ln51_fu_259_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_2_fu_119_p4 <= layer2_out_dout(19 downto 10);
    out_data_3_fu_279_p3 <= 
        trunc_ln44_1_fu_129_p4 when (icmp_ln51_1_fu_273_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_4_fu_139_p4 <= layer2_out_dout(29 downto 20);
    out_data_5_fu_293_p3 <= 
        trunc_ln44_2_fu_149_p4 when (icmp_ln51_2_fu_287_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_6_fu_159_p4 <= layer2_out_dout(39 downto 30);
    out_data_7_fu_307_p3 <= 
        trunc_ln44_3_fu_169_p4 when (icmp_ln51_3_fu_301_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_fu_111_p1 <= layer2_out_dout(10 - 1 downto 0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_1_fu_335_p3 <= 
        trunc_ln44_9_fu_209_p4 when (icmp_ln51_5_fu_329_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_2_fu_349_p3 <= 
        trunc_ln44_s_fu_229_p4 when (icmp_ln51_6_fu_343_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_3_fu_363_p3 <= 
        trunc_ln_fu_249_p4 when (icmp_ln51_7_fu_357_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_fu_321_p3 <= 
        trunc_ln44_8_fu_189_p4 when (icmp_ln51_4_fu_315_p2(0) = '1') else 
        ap_const_lv9_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_11_fu_115_p1 <= layer2_out_dout(9 - 1 downto 0);
    trunc_ln44_1_fu_129_p4 <= layer2_out_dout(18 downto 10);
    trunc_ln44_2_fu_149_p4 <= layer2_out_dout(28 downto 20);
    trunc_ln44_3_fu_169_p4 <= layer2_out_dout(38 downto 30);
    trunc_ln44_4_fu_179_p4 <= layer2_out_dout(49 downto 40);
    trunc_ln44_5_fu_199_p4 <= layer2_out_dout(59 downto 50);
    trunc_ln44_6_fu_219_p4 <= layer2_out_dout(69 downto 60);
    trunc_ln44_7_fu_239_p4 <= layer2_out_dout(79 downto 70);
    trunc_ln44_8_fu_189_p4 <= layer2_out_dout(48 downto 40);
    trunc_ln44_9_fu_209_p4 <= layer2_out_dout(58 downto 50);
    trunc_ln44_s_fu_229_p4 <= layer2_out_dout(68 downto 60);
    trunc_ln_fu_249_p4 <= layer2_out_dout(78 downto 70);
    zext_ln45_1_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_3_reg_445),10));
    zext_ln45_2_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_5_reg_450),10));
    zext_ln45_3_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_7_reg_455),10));
    zext_ln45_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_1_reg_440),10));
    zext_ln51_1_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_1_reg_465),10));
    zext_ln51_2_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_2_reg_470),10));
    zext_ln51_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_460),10));
    zext_ln57_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_409_p9),80));
end behav;
