-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer15_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
    layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer15_out_empty_n : IN STD_LOGIC;
    layer15_out_read : OUT STD_LOGIC;
    layer17_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
    layer17_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_full_n : IN STD_LOGIC;
    layer17_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010100";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110010";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011010";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100100";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000100";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001100";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010110";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_121 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100001";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101010";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_135 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110101";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer15_out_blk_n : STD_LOGIC;
    signal layer17_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln51_fu_861_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_reg_1468 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal select_ln51_4_fu_875_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_4_reg_1473 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_5_fu_889_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_5_reg_1478 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_6_fu_903_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_6_reg_1483 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_7_fu_917_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_7_reg_1488 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_8_fu_931_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_8_reg_1493 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_9_fu_945_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_9_reg_1498 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_10_fu_959_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_10_reg_1503 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_11_fu_973_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_11_reg_1508 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_12_fu_987_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_12_reg_1513 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_13_fu_1001_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_13_reg_1518 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_14_fu_1015_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_14_reg_1523 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_15_fu_1029_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_15_reg_1528 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_16_fu_1043_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_16_reg_1533 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_17_fu_1057_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_17_reg_1538 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_18_fu_1071_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_18_reg_1543 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_19_fu_1085_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_19_reg_1548 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_20_fu_1099_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_20_reg_1553 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_21_fu_1113_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_21_reg_1558 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_22_fu_1127_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_22_reg_1563 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_23_fu_1141_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_23_reg_1568 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_24_fu_1155_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_24_reg_1573 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_25_fu_1169_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_25_reg_1578 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_26_fu_1183_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_26_reg_1583 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_27_fu_1197_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_27_reg_1588 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_28_fu_1211_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_28_reg_1593 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_29_fu_1225_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_29_reg_1598 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_30_fu_1239_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_30_reg_1603 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_31_fu_1253_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_31_reg_1608 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_32_fu_1267_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_32_reg_1613 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_33_fu_1281_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_33_reg_1618 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_34_fu_1295_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_34_reg_1623 : STD_LOGIC_VECTOR (8 downto 0);
    signal layer15_out_read_local : STD_LOGIC;
    signal zext_ln57_fu_1463_p1 : STD_LOGIC_VECTOR (319 downto 0);
    signal layer17_out_write_local : STD_LOGIC;
    signal trunc_ln44_fu_227_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_69_fu_231_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_8_fu_235_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_8_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_s_fu_245_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_9_fu_255_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_9_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_1_fu_265_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_2_fu_275_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_10_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_3_fu_285_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_4_fu_295_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_11_fu_911_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_5_fu_305_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_6_fu_315_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_12_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_7_fu_325_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_10_fu_335_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_13_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_11_fu_345_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_12_fu_355_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_14_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_13_fu_365_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_14_fu_375_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_15_fu_967_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_15_fu_385_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_16_fu_395_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_16_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_39_fu_405_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_17_fu_415_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_17_fu_995_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_40_fu_425_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_18_fu_435_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_18_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_41_fu_445_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_19_fu_455_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_19_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_42_fu_465_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_20_fu_475_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_20_fu_1037_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_43_fu_485_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_21_fu_495_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_21_fu_1051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_44_fu_505_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_22_fu_515_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_22_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_45_fu_525_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_23_fu_535_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_23_fu_1079_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_46_fu_545_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_24_fu_555_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_24_fu_1093_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_47_fu_565_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_25_fu_575_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_25_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_48_fu_585_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_26_fu_595_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_26_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_49_fu_605_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_27_fu_615_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_27_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_50_fu_625_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_28_fu_635_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_28_fu_1149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_51_fu_645_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_29_fu_655_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_29_fu_1163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_52_fu_665_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_30_fu_675_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_30_fu_1177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_53_fu_685_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_31_fu_695_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_31_fu_1191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_54_fu_705_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_32_fu_715_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_32_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_55_fu_725_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_33_fu_735_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_33_fu_1219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_56_fu_745_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_34_fu_755_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_34_fu_1233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_57_fu_765_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_35_fu_775_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_35_fu_1247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_58_fu_785_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_36_fu_795_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_36_fu_1261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_59_fu_805_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_37_fu_815_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_37_fu_1275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_60_fu_825_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_38_fu_835_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_38_fu_1289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_845_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln51_32_fu_1393_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_31_fu_1390_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_30_fu_1387_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_29_fu_1384_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_28_fu_1381_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_27_fu_1378_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_26_fu_1375_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_25_fu_1372_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_24_fu_1369_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_23_fu_1366_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_22_fu_1363_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_21_fu_1360_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_20_fu_1357_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_19_fu_1354_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_18_fu_1351_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_17_fu_1348_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_16_fu_1345_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_15_fu_1342_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_14_fu_1339_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_13_fu_1336_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_12_fu_1333_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_11_fu_1330_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_10_fu_1327_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_9_fu_1324_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_8_fu_1321_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_7_fu_1318_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_6_fu_1315_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_5_fu_1312_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_4_fu_1309_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_3_fu_1306_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_fu_1303_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln57_s_fu_1396_p33 : STD_LOGIC_VECTOR (318 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                select_ln51_10_reg_1503 <= select_ln51_10_fu_959_p3;
                select_ln51_11_reg_1508 <= select_ln51_11_fu_973_p3;
                select_ln51_12_reg_1513 <= select_ln51_12_fu_987_p3;
                select_ln51_13_reg_1518 <= select_ln51_13_fu_1001_p3;
                select_ln51_14_reg_1523 <= select_ln51_14_fu_1015_p3;
                select_ln51_15_reg_1528 <= select_ln51_15_fu_1029_p3;
                select_ln51_16_reg_1533 <= select_ln51_16_fu_1043_p3;
                select_ln51_17_reg_1538 <= select_ln51_17_fu_1057_p3;
                select_ln51_18_reg_1543 <= select_ln51_18_fu_1071_p3;
                select_ln51_19_reg_1548 <= select_ln51_19_fu_1085_p3;
                select_ln51_20_reg_1553 <= select_ln51_20_fu_1099_p3;
                select_ln51_21_reg_1558 <= select_ln51_21_fu_1113_p3;
                select_ln51_22_reg_1563 <= select_ln51_22_fu_1127_p3;
                select_ln51_23_reg_1568 <= select_ln51_23_fu_1141_p3;
                select_ln51_24_reg_1573 <= select_ln51_24_fu_1155_p3;
                select_ln51_25_reg_1578 <= select_ln51_25_fu_1169_p3;
                select_ln51_26_reg_1583 <= select_ln51_26_fu_1183_p3;
                select_ln51_27_reg_1588 <= select_ln51_27_fu_1197_p3;
                select_ln51_28_reg_1593 <= select_ln51_28_fu_1211_p3;
                select_ln51_29_reg_1598 <= select_ln51_29_fu_1225_p3;
                select_ln51_30_reg_1603 <= select_ln51_30_fu_1239_p3;
                select_ln51_31_reg_1608 <= select_ln51_31_fu_1253_p3;
                select_ln51_32_reg_1613 <= select_ln51_32_fu_1267_p3;
                select_ln51_33_reg_1618 <= select_ln51_33_fu_1281_p3;
                select_ln51_34_reg_1623 <= select_ln51_34_fu_1295_p3;
                select_ln51_4_reg_1473 <= select_ln51_4_fu_875_p3;
                select_ln51_5_reg_1478 <= select_ln51_5_fu_889_p3;
                select_ln51_6_reg_1483 <= select_ln51_6_fu_903_p3;
                select_ln51_7_reg_1488 <= select_ln51_7_fu_917_p3;
                select_ln51_8_reg_1493 <= select_ln51_8_fu_931_p3;
                select_ln51_9_reg_1498 <= select_ln51_9_fu_945_p3;
                select_ln51_reg_1468 <= select_ln51_fu_861_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer17_out_full_n, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer17_out_full_n)
    begin
        if ((layer17_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer15_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer15_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer17_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln51_10_fu_897_p2 <= "1" when (signed(trunc_ln44_2_fu_275_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_11_fu_911_p2 <= "1" when (signed(trunc_ln44_4_fu_295_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_12_fu_925_p2 <= "1" when (signed(trunc_ln44_6_fu_315_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_13_fu_939_p2 <= "1" when (signed(trunc_ln44_10_fu_335_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_14_fu_953_p2 <= "1" when (signed(trunc_ln44_12_fu_355_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_15_fu_967_p2 <= "1" when (signed(trunc_ln44_14_fu_375_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_16_fu_981_p2 <= "1" when (signed(trunc_ln44_16_fu_395_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_17_fu_995_p2 <= "1" when (signed(trunc_ln44_17_fu_415_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_18_fu_1009_p2 <= "1" when (signed(trunc_ln44_18_fu_435_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_19_fu_1023_p2 <= "1" when (signed(trunc_ln44_19_fu_455_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_20_fu_1037_p2 <= "1" when (signed(trunc_ln44_20_fu_475_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_21_fu_1051_p2 <= "1" when (signed(trunc_ln44_21_fu_495_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_22_fu_1065_p2 <= "1" when (signed(trunc_ln44_22_fu_515_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_23_fu_1079_p2 <= "1" when (signed(trunc_ln44_23_fu_535_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_24_fu_1093_p2 <= "1" when (signed(trunc_ln44_24_fu_555_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_25_fu_1107_p2 <= "1" when (signed(trunc_ln44_25_fu_575_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_26_fu_1121_p2 <= "1" when (signed(trunc_ln44_26_fu_595_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_27_fu_1135_p2 <= "1" when (signed(trunc_ln44_27_fu_615_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_28_fu_1149_p2 <= "1" when (signed(trunc_ln44_28_fu_635_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_29_fu_1163_p2 <= "1" when (signed(trunc_ln44_29_fu_655_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_30_fu_1177_p2 <= "1" when (signed(trunc_ln44_30_fu_675_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_31_fu_1191_p2 <= "1" when (signed(trunc_ln44_31_fu_695_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_32_fu_1205_p2 <= "1" when (signed(trunc_ln44_32_fu_715_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_33_fu_1219_p2 <= "1" when (signed(trunc_ln44_33_fu_735_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_34_fu_1233_p2 <= "1" when (signed(trunc_ln44_34_fu_755_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_35_fu_1247_p2 <= "1" when (signed(trunc_ln44_35_fu_775_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_36_fu_1261_p2 <= "1" when (signed(trunc_ln44_36_fu_795_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_37_fu_1275_p2 <= "1" when (signed(trunc_ln44_37_fu_815_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_38_fu_1289_p2 <= "1" when (signed(trunc_ln44_38_fu_835_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_8_fu_869_p2 <= "1" when (signed(trunc_ln44_8_fu_235_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_9_fu_883_p2 <= "1" when (signed(trunc_ln44_9_fu_255_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_fu_855_p2 <= "1" when (signed(trunc_ln44_fu_227_p1) > signed(ap_const_lv10_0)) else "0";

    internal_ap_ready_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer15_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer15_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer15_out_blk_n <= layer15_out_empty_n;
        else 
            layer15_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer15_out_read <= layer15_out_read_local;

    layer15_out_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer15_out_read_local <= ap_const_logic_1;
        else 
            layer15_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_blk_n_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer17_out_blk_n <= layer17_out_full_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer17_out_din <= zext_ln57_fu_1463_p1;
    layer17_out_write <= layer17_out_write_local;

    layer17_out_write_local_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer17_out_write_local <= ap_const_logic_1;
        else 
            layer17_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1396_p33 <= (((((((((((((((((((((((((((((((select_ln51_34_reg_1623 & zext_ln51_32_fu_1393_p1) & zext_ln51_31_fu_1390_p1) & zext_ln51_30_fu_1387_p1) & zext_ln51_29_fu_1384_p1) & zext_ln51_28_fu_1381_p1) & zext_ln51_27_fu_1378_p1) & zext_ln51_26_fu_1375_p1) & zext_ln51_25_fu_1372_p1) & zext_ln51_24_fu_1369_p1) & zext_ln51_23_fu_1366_p1) & zext_ln51_22_fu_1363_p1) & zext_ln51_21_fu_1360_p1) & zext_ln51_20_fu_1357_p1) & zext_ln51_19_fu_1354_p1) & zext_ln51_18_fu_1351_p1) & zext_ln51_17_fu_1348_p1) & zext_ln51_16_fu_1345_p1) & zext_ln51_15_fu_1342_p1) & zext_ln51_14_fu_1339_p1) & zext_ln51_13_fu_1336_p1) & zext_ln51_12_fu_1333_p1) & zext_ln51_11_fu_1330_p1) & zext_ln51_10_fu_1327_p1) & zext_ln51_9_fu_1324_p1) & zext_ln51_8_fu_1321_p1) & zext_ln51_7_fu_1318_p1) & zext_ln51_6_fu_1315_p1) & zext_ln51_5_fu_1312_p1) & zext_ln51_4_fu_1309_p1) & zext_ln51_3_fu_1306_p1) & zext_ln51_fu_1303_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_10_fu_959_p3 <= 
        trunc_ln44_13_fu_365_p4 when (icmp_ln51_14_fu_953_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_11_fu_973_p3 <= 
        trunc_ln44_15_fu_385_p4 when (icmp_ln51_15_fu_967_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_12_fu_987_p3 <= 
        trunc_ln44_39_fu_405_p4 when (icmp_ln51_16_fu_981_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_13_fu_1001_p3 <= 
        trunc_ln44_40_fu_425_p4 when (icmp_ln51_17_fu_995_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_14_fu_1015_p3 <= 
        trunc_ln44_41_fu_445_p4 when (icmp_ln51_18_fu_1009_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_15_fu_1029_p3 <= 
        trunc_ln44_42_fu_465_p4 when (icmp_ln51_19_fu_1023_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_16_fu_1043_p3 <= 
        trunc_ln44_43_fu_485_p4 when (icmp_ln51_20_fu_1037_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_17_fu_1057_p3 <= 
        trunc_ln44_44_fu_505_p4 when (icmp_ln51_21_fu_1051_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_18_fu_1071_p3 <= 
        trunc_ln44_45_fu_525_p4 when (icmp_ln51_22_fu_1065_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_19_fu_1085_p3 <= 
        trunc_ln44_46_fu_545_p4 when (icmp_ln51_23_fu_1079_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_20_fu_1099_p3 <= 
        trunc_ln44_47_fu_565_p4 when (icmp_ln51_24_fu_1093_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_21_fu_1113_p3 <= 
        trunc_ln44_48_fu_585_p4 when (icmp_ln51_25_fu_1107_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_22_fu_1127_p3 <= 
        trunc_ln44_49_fu_605_p4 when (icmp_ln51_26_fu_1121_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_23_fu_1141_p3 <= 
        trunc_ln44_50_fu_625_p4 when (icmp_ln51_27_fu_1135_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_24_fu_1155_p3 <= 
        trunc_ln44_51_fu_645_p4 when (icmp_ln51_28_fu_1149_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_25_fu_1169_p3 <= 
        trunc_ln44_52_fu_665_p4 when (icmp_ln51_29_fu_1163_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_26_fu_1183_p3 <= 
        trunc_ln44_53_fu_685_p4 when (icmp_ln51_30_fu_1177_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_27_fu_1197_p3 <= 
        trunc_ln44_54_fu_705_p4 when (icmp_ln51_31_fu_1191_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_28_fu_1211_p3 <= 
        trunc_ln44_55_fu_725_p4 when (icmp_ln51_32_fu_1205_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_29_fu_1225_p3 <= 
        trunc_ln44_56_fu_745_p4 when (icmp_ln51_33_fu_1219_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_30_fu_1239_p3 <= 
        trunc_ln44_57_fu_765_p4 when (icmp_ln51_34_fu_1233_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_31_fu_1253_p3 <= 
        trunc_ln44_58_fu_785_p4 when (icmp_ln51_35_fu_1247_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_32_fu_1267_p3 <= 
        trunc_ln44_59_fu_805_p4 when (icmp_ln51_36_fu_1261_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_33_fu_1281_p3 <= 
        trunc_ln44_60_fu_825_p4 when (icmp_ln51_37_fu_1275_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_34_fu_1295_p3 <= 
        trunc_ln1_fu_845_p4 when (icmp_ln51_38_fu_1289_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_4_fu_875_p3 <= 
        trunc_ln44_s_fu_245_p4 when (icmp_ln51_8_fu_869_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_5_fu_889_p3 <= 
        trunc_ln44_1_fu_265_p4 when (icmp_ln51_9_fu_883_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_6_fu_903_p3 <= 
        trunc_ln44_3_fu_285_p4 when (icmp_ln51_10_fu_897_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_7_fu_917_p3 <= 
        trunc_ln44_5_fu_305_p4 when (icmp_ln51_11_fu_911_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_8_fu_931_p3 <= 
        trunc_ln44_7_fu_325_p4 when (icmp_ln51_12_fu_925_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_9_fu_945_p3 <= 
        trunc_ln44_11_fu_345_p4 when (icmp_ln51_13_fu_939_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_fu_861_p3 <= 
        trunc_ln44_69_fu_231_p1 when (icmp_ln51_fu_855_p2(0) = '1') else 
        ap_const_lv9_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1_fu_845_p4 <= layer15_out_dout(318 downto 310);
    trunc_ln44_10_fu_335_p4 <= layer15_out_dout(69 downto 60);
    trunc_ln44_11_fu_345_p4 <= layer15_out_dout(68 downto 60);
    trunc_ln44_12_fu_355_p4 <= layer15_out_dout(79 downto 70);
    trunc_ln44_13_fu_365_p4 <= layer15_out_dout(78 downto 70);
    trunc_ln44_14_fu_375_p4 <= layer15_out_dout(89 downto 80);
    trunc_ln44_15_fu_385_p4 <= layer15_out_dout(88 downto 80);
    trunc_ln44_16_fu_395_p4 <= layer15_out_dout(99 downto 90);
    trunc_ln44_17_fu_415_p4 <= layer15_out_dout(109 downto 100);
    trunc_ln44_18_fu_435_p4 <= layer15_out_dout(119 downto 110);
    trunc_ln44_19_fu_455_p4 <= layer15_out_dout(129 downto 120);
    trunc_ln44_1_fu_265_p4 <= layer15_out_dout(28 downto 20);
    trunc_ln44_20_fu_475_p4 <= layer15_out_dout(139 downto 130);
    trunc_ln44_21_fu_495_p4 <= layer15_out_dout(149 downto 140);
    trunc_ln44_22_fu_515_p4 <= layer15_out_dout(159 downto 150);
    trunc_ln44_23_fu_535_p4 <= layer15_out_dout(169 downto 160);
    trunc_ln44_24_fu_555_p4 <= layer15_out_dout(179 downto 170);
    trunc_ln44_25_fu_575_p4 <= layer15_out_dout(189 downto 180);
    trunc_ln44_26_fu_595_p4 <= layer15_out_dout(199 downto 190);
    trunc_ln44_27_fu_615_p4 <= layer15_out_dout(209 downto 200);
    trunc_ln44_28_fu_635_p4 <= layer15_out_dout(219 downto 210);
    trunc_ln44_29_fu_655_p4 <= layer15_out_dout(229 downto 220);
    trunc_ln44_2_fu_275_p4 <= layer15_out_dout(39 downto 30);
    trunc_ln44_30_fu_675_p4 <= layer15_out_dout(239 downto 230);
    trunc_ln44_31_fu_695_p4 <= layer15_out_dout(249 downto 240);
    trunc_ln44_32_fu_715_p4 <= layer15_out_dout(259 downto 250);
    trunc_ln44_33_fu_735_p4 <= layer15_out_dout(269 downto 260);
    trunc_ln44_34_fu_755_p4 <= layer15_out_dout(279 downto 270);
    trunc_ln44_35_fu_775_p4 <= layer15_out_dout(289 downto 280);
    trunc_ln44_36_fu_795_p4 <= layer15_out_dout(299 downto 290);
    trunc_ln44_37_fu_815_p4 <= layer15_out_dout(309 downto 300);
    trunc_ln44_38_fu_835_p4 <= layer15_out_dout(319 downto 310);
    trunc_ln44_39_fu_405_p4 <= layer15_out_dout(98 downto 90);
    trunc_ln44_3_fu_285_p4 <= layer15_out_dout(38 downto 30);
    trunc_ln44_40_fu_425_p4 <= layer15_out_dout(108 downto 100);
    trunc_ln44_41_fu_445_p4 <= layer15_out_dout(118 downto 110);
    trunc_ln44_42_fu_465_p4 <= layer15_out_dout(128 downto 120);
    trunc_ln44_43_fu_485_p4 <= layer15_out_dout(138 downto 130);
    trunc_ln44_44_fu_505_p4 <= layer15_out_dout(148 downto 140);
    trunc_ln44_45_fu_525_p4 <= layer15_out_dout(158 downto 150);
    trunc_ln44_46_fu_545_p4 <= layer15_out_dout(168 downto 160);
    trunc_ln44_47_fu_565_p4 <= layer15_out_dout(178 downto 170);
    trunc_ln44_48_fu_585_p4 <= layer15_out_dout(188 downto 180);
    trunc_ln44_49_fu_605_p4 <= layer15_out_dout(198 downto 190);
    trunc_ln44_4_fu_295_p4 <= layer15_out_dout(49 downto 40);
    trunc_ln44_50_fu_625_p4 <= layer15_out_dout(208 downto 200);
    trunc_ln44_51_fu_645_p4 <= layer15_out_dout(218 downto 210);
    trunc_ln44_52_fu_665_p4 <= layer15_out_dout(228 downto 220);
    trunc_ln44_53_fu_685_p4 <= layer15_out_dout(238 downto 230);
    trunc_ln44_54_fu_705_p4 <= layer15_out_dout(248 downto 240);
    trunc_ln44_55_fu_725_p4 <= layer15_out_dout(258 downto 250);
    trunc_ln44_56_fu_745_p4 <= layer15_out_dout(268 downto 260);
    trunc_ln44_57_fu_765_p4 <= layer15_out_dout(278 downto 270);
    trunc_ln44_58_fu_785_p4 <= layer15_out_dout(288 downto 280);
    trunc_ln44_59_fu_805_p4 <= layer15_out_dout(298 downto 290);
    trunc_ln44_5_fu_305_p4 <= layer15_out_dout(48 downto 40);
    trunc_ln44_60_fu_825_p4 <= layer15_out_dout(308 downto 300);
    trunc_ln44_69_fu_231_p1 <= layer15_out_dout(9 - 1 downto 0);
    trunc_ln44_6_fu_315_p4 <= layer15_out_dout(59 downto 50);
    trunc_ln44_7_fu_325_p4 <= layer15_out_dout(58 downto 50);
    trunc_ln44_8_fu_235_p4 <= layer15_out_dout(19 downto 10);
    trunc_ln44_9_fu_255_p4 <= layer15_out_dout(29 downto 20);
    trunc_ln44_fu_227_p1 <= layer15_out_dout(10 - 1 downto 0);
    trunc_ln44_s_fu_245_p4 <= layer15_out_dout(18 downto 10);
    zext_ln51_10_fu_1327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_11_reg_1508),10));
    zext_ln51_11_fu_1330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_12_reg_1513),10));
    zext_ln51_12_fu_1333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_13_reg_1518),10));
    zext_ln51_13_fu_1336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_14_reg_1523),10));
    zext_ln51_14_fu_1339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_15_reg_1528),10));
    zext_ln51_15_fu_1342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_16_reg_1533),10));
    zext_ln51_16_fu_1345_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_17_reg_1538),10));
    zext_ln51_17_fu_1348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_18_reg_1543),10));
    zext_ln51_18_fu_1351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_19_reg_1548),10));
    zext_ln51_19_fu_1354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_20_reg_1553),10));
    zext_ln51_20_fu_1357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_21_reg_1558),10));
    zext_ln51_21_fu_1360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_22_reg_1563),10));
    zext_ln51_22_fu_1363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_23_reg_1568),10));
    zext_ln51_23_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_24_reg_1573),10));
    zext_ln51_24_fu_1369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_25_reg_1578),10));
    zext_ln51_25_fu_1372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_26_reg_1583),10));
    zext_ln51_26_fu_1375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_27_reg_1588),10));
    zext_ln51_27_fu_1378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_28_reg_1593),10));
    zext_ln51_28_fu_1381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_29_reg_1598),10));
    zext_ln51_29_fu_1384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_30_reg_1603),10));
    zext_ln51_30_fu_1387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_31_reg_1608),10));
    zext_ln51_31_fu_1390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_32_reg_1613),10));
    zext_ln51_32_fu_1393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_33_reg_1618),10));
    zext_ln51_3_fu_1306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_4_reg_1473),10));
    zext_ln51_4_fu_1309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_5_reg_1478),10));
    zext_ln51_5_fu_1312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_6_reg_1483),10));
    zext_ln51_6_fu_1315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_7_reg_1488),10));
    zext_ln51_7_fu_1318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_8_reg_1493),10));
    zext_ln51_8_fu_1321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_9_reg_1498),10));
    zext_ln51_9_fu_1324_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_10_reg_1503),10));
    zext_ln51_fu_1303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_1468),10));
    zext_ln57_fu_1463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1396_p33),320));
end behav;
