-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer22_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
    layer22_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer22_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer22_out_empty_n : IN STD_LOGIC;
    layer22_out_read : OUT STD_LOGIC;
    layer10_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
    layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    layer10_out_full_n : IN STD_LOGIC;
    layer10_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_64 : STD_LOGIC_VECTOR (6 downto 0) := "1100100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer22_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln79_fu_860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln87_fu_872_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_reg_1057 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal trunc_ln87_s_reg_1062 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_1_reg_1067 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_2_reg_1072 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_3_reg_1077 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_4_reg_1082 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_5_reg_1087 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_6_reg_1092 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_7_reg_1097 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_8_reg_1102 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_9_reg_1107 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_10_reg_1112 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_11_reg_1117 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_12_reg_1122 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_13_reg_1127 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln87_14_reg_1132 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call19 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal indvar_flatten_fu_458 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln79_fu_866_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal layer22_out_read_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (9 downto 0);
        layer10_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        layer10_out_full_n : IN STD_LOGIC;
        layer10_out_write : OUT STD_LOGIC );
    end component;



begin
    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468 : component myproject_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start,
        ap_done => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done,
        ap_idle => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_idle,
        ap_ready => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready,
        p_read => trunc_ln87_reg_1057,
        p_read1 => trunc_ln87_s_reg_1062,
        p_read2 => trunc_ln87_1_reg_1067,
        p_read3 => trunc_ln87_2_reg_1072,
        p_read4 => trunc_ln87_3_reg_1077,
        p_read5 => trunc_ln87_4_reg_1082,
        p_read6 => trunc_ln87_5_reg_1087,
        p_read7 => trunc_ln87_6_reg_1092,
        p_read8 => trunc_ln87_7_reg_1097,
        p_read9 => trunc_ln87_8_reg_1102,
        p_read10 => trunc_ln87_9_reg_1107,
        p_read11 => trunc_ln87_10_reg_1112,
        p_read12 => trunc_ln87_11_reg_1117,
        p_read13 => trunc_ln87_12_reg_1122,
        p_read14 => trunc_ln87_13_reg_1127,
        p_read15 => trunc_ln87_14_reg_1132,
        layer10_out_din => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din,
        layer10_out_num_data_valid => ap_const_lv7_0,
        layer10_out_fifo_cap => ap_const_lv7_0,
        layer10_out_full_n => layer10_out_full_n,
        layer10_out_write => grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_ignore_call19) and (icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_458_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_fu_458 <= ap_const_lv7_0;
            elsif (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvar_flatten_fu_458 <= add_ln79_fu_866_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln87_10_reg_1112 <= layer22_out_dout(119 downto 110);
                trunc_ln87_11_reg_1117 <= layer22_out_dout(129 downto 120);
                trunc_ln87_12_reg_1122 <= layer22_out_dout(139 downto 130);
                trunc_ln87_13_reg_1127 <= layer22_out_dout(149 downto 140);
                trunc_ln87_14_reg_1132 <= layer22_out_dout(159 downto 150);
                trunc_ln87_1_reg_1067 <= layer22_out_dout(29 downto 20);
                trunc_ln87_2_reg_1072 <= layer22_out_dout(39 downto 30);
                trunc_ln87_3_reg_1077 <= layer22_out_dout(49 downto 40);
                trunc_ln87_4_reg_1082 <= layer22_out_dout(59 downto 50);
                trunc_ln87_5_reg_1087 <= layer22_out_dout(69 downto 60);
                trunc_ln87_6_reg_1092 <= layer22_out_dout(79 downto 70);
                trunc_ln87_7_reg_1097 <= layer22_out_dout(89 downto 80);
                trunc_ln87_8_reg_1102 <= layer22_out_dout(99 downto 90);
                trunc_ln87_9_reg_1107 <= layer22_out_dout(109 downto 100);
                trunc_ln87_reg_1057 <= trunc_ln87_fu_872_p1;
                trunc_ln87_s_reg_1062 <= layer22_out_dout(19 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln79_fu_860_p2, ap_block_state2, grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln79_fu_866_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_458) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done)
    begin
        if ((grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(layer22_out_empty_n, icmp_ln79_fu_860_p2)
    begin
                ap_block_state2 <= ((icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (layer22_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call19_assign_proc : process(layer22_out_empty_n, icmp_ln79_fu_860_p2)
    begin
                ap_block_state2_ignore_call19 <= ((icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (layer22_out_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln79_fu_860_p2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start <= grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg;
    icmp_ln79_fu_860_p2 <= "1" when (indvar_flatten_fu_458 = ap_const_lv7_64) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln79_fu_860_p2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    layer10_out_din <= grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din;

    layer10_out_write_assign_proc : process(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer10_out_write <= grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write;
        else 
            layer10_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer22_out_blk_n_assign_proc : process(layer22_out_empty_n, ap_CS_fsm_state2, icmp_ln79_fu_860_p2)
    begin
        if (((icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer22_out_blk_n <= layer22_out_empty_n;
        else 
            layer22_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer22_out_read <= layer22_out_read_local;

    layer22_out_read_local_assign_proc : process(ap_CS_fsm_state2, icmp_ln79_fu_860_p2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (icmp_ln79_fu_860_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer22_out_read_local <= ap_const_logic_1;
        else 
            layer22_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln87_fu_872_p1 <= layer22_out_dout(10 - 1 downto 0);
end behav;
