-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer10_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
    layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    layer10_out_empty_n : IN STD_LOGIC;
    layer10_out_read : OUT STD_LOGIC;
    layer12_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
    layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    layer12_out_full_n : IN STD_LOGIC;
    layer12_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010100";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110010";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011010";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100100";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000100";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001100";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010110";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_121 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100001";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101010";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_135 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110101";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_1339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer10_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer12_out_blk_n : STD_LOGIC;
    signal out_data_8_fu_891_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_8_reg_1522 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal out_data_10_fu_905_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_10_reg_1527 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_12_fu_919_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_12_reg_1532 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_13_fu_933_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_13_reg_1537 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_fu_947_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_reg_1542 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_35_fu_961_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_35_reg_1547 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_36_fu_975_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_36_reg_1552 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_37_fu_989_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_37_reg_1557 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_38_fu_1003_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_38_reg_1562 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_39_fu_1017_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_39_reg_1567 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_40_fu_1031_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_40_reg_1572 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_41_fu_1045_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_41_reg_1577 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_42_fu_1059_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_42_reg_1582 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_43_fu_1073_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_43_reg_1587 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_44_fu_1087_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_44_reg_1592 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_45_fu_1101_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_45_reg_1597 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_46_fu_1115_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_46_reg_1602 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_47_fu_1129_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_47_reg_1607 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_48_fu_1143_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_48_reg_1612 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_49_fu_1157_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_49_reg_1617 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_50_fu_1171_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_50_reg_1622 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_51_fu_1185_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_51_reg_1627 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_52_fu_1199_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_52_reg_1632 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_53_fu_1213_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_53_reg_1637 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_54_fu_1227_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_54_reg_1642 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_55_fu_1241_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_55_reg_1647 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_56_fu_1255_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_56_reg_1652 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_57_fu_1269_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_57_reg_1657 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_58_fu_1283_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_58_reg_1662 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_59_fu_1297_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_59_reg_1667 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_60_fu_1311_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_60_reg_1672 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_61_fu_1325_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_61_reg_1677 : STD_LOGIC_VECTOR (8 downto 0);
    signal i1_fu_232 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal i_fu_1333_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_read_local : STD_LOGIC;
    signal zext_ln57_fu_1510_p1 : STD_LOGIC_VECTOR (319 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal layer12_out_write_local : STD_LOGIC;
    signal out_data_fu_257_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_100_fu_261_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_9_fu_265_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_39_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_s_fu_275_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_11_fu_285_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_40_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_70_fu_295_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_1_fu_305_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_41_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_71_fu_315_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_42_fu_325_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_42_fu_941_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_72_fu_335_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_43_fu_345_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_43_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_73_fu_355_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_44_fu_365_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_44_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_74_fu_375_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_45_fu_385_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_45_fu_983_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_75_fu_395_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_46_fu_405_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_46_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_76_fu_415_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_47_fu_425_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_47_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_77_fu_435_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_48_fu_445_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_48_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_78_fu_455_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_49_fu_465_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_49_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_79_fu_475_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_50_fu_485_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_50_fu_1053_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_80_fu_495_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_51_fu_505_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_51_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_81_fu_515_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_52_fu_525_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_52_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_82_fu_535_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_53_fu_545_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_53_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_83_fu_555_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_54_fu_565_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_54_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_84_fu_575_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_55_fu_585_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_55_fu_1123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_85_fu_595_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_56_fu_605_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_56_fu_1137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_86_fu_615_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_57_fu_625_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_57_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_87_fu_635_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_58_fu_645_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_58_fu_1165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_88_fu_655_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_59_fu_665_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_59_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_89_fu_675_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_60_fu_685_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_60_fu_1193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_90_fu_695_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_61_fu_705_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_61_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_91_fu_715_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_62_fu_725_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_62_fu_1221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_92_fu_735_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_63_fu_745_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_63_fu_1235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_93_fu_755_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_64_fu_765_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_64_fu_1249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_94_fu_775_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_65_fu_785_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_65_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_95_fu_795_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_66_fu_805_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_66_fu_1277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_96_fu_815_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_67_fu_825_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_67_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_97_fu_835_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_68_fu_845_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_68_fu_1305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_98_fu_855_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_69_fu_865_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln51_69_fu_1319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_875_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln51_58_fu_1440_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_57_fu_1437_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_56_fu_1434_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_55_fu_1431_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_54_fu_1428_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_53_fu_1425_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_52_fu_1422_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_51_fu_1419_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_50_fu_1416_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_49_fu_1413_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_48_fu_1410_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_47_fu_1407_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_46_fu_1404_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_45_fu_1401_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_44_fu_1398_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_43_fu_1395_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_42_fu_1392_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_41_fu_1389_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_40_fu_1386_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_39_fu_1383_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_38_fu_1380_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_37_fu_1377_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_36_fu_1374_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_35_fu_1371_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_34_fu_1368_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_33_fu_1365_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_fu_1362_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_6_fu_1359_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_5_fu_1356_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_4_fu_1353_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln45_fu_1350_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln57_s_fu_1443_p33 : STD_LOGIC_VECTOR (318 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_171 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i1_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_171)) then
                i1_fu_232 <= i_fu_1333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_data_10_reg_1527 <= out_data_10_fu_905_p3;
                out_data_12_reg_1532 <= out_data_12_fu_919_p3;
                out_data_13_reg_1537 <= out_data_13_fu_933_p3;
                out_data_8_reg_1522 <= out_data_8_fu_891_p3;
                select_ln51_35_reg_1547 <= select_ln51_35_fu_961_p3;
                select_ln51_36_reg_1552 <= select_ln51_36_fu_975_p3;
                select_ln51_37_reg_1557 <= select_ln51_37_fu_989_p3;
                select_ln51_38_reg_1562 <= select_ln51_38_fu_1003_p3;
                select_ln51_39_reg_1567 <= select_ln51_39_fu_1017_p3;
                select_ln51_40_reg_1572 <= select_ln51_40_fu_1031_p3;
                select_ln51_41_reg_1577 <= select_ln51_41_fu_1045_p3;
                select_ln51_42_reg_1582 <= select_ln51_42_fu_1059_p3;
                select_ln51_43_reg_1587 <= select_ln51_43_fu_1073_p3;
                select_ln51_44_reg_1592 <= select_ln51_44_fu_1087_p3;
                select_ln51_45_reg_1597 <= select_ln51_45_fu_1101_p3;
                select_ln51_46_reg_1602 <= select_ln51_46_fu_1115_p3;
                select_ln51_47_reg_1607 <= select_ln51_47_fu_1129_p3;
                select_ln51_48_reg_1612 <= select_ln51_48_fu_1143_p3;
                select_ln51_49_reg_1617 <= select_ln51_49_fu_1157_p3;
                select_ln51_50_reg_1622 <= select_ln51_50_fu_1171_p3;
                select_ln51_51_reg_1627 <= select_ln51_51_fu_1185_p3;
                select_ln51_52_reg_1632 <= select_ln51_52_fu_1199_p3;
                select_ln51_53_reg_1637 <= select_ln51_53_fu_1213_p3;
                select_ln51_54_reg_1642 <= select_ln51_54_fu_1227_p3;
                select_ln51_55_reg_1647 <= select_ln51_55_fu_1241_p3;
                select_ln51_56_reg_1652 <= select_ln51_56_fu_1255_p3;
                select_ln51_57_reg_1657 <= select_ln51_57_fu_1269_p3;
                select_ln51_58_reg_1662 <= select_ln51_58_fu_1283_p3;
                select_ln51_59_reg_1667 <= select_ln51_59_fu_1297_p3;
                select_ln51_60_reg_1672 <= select_ln51_60_fu_1311_p3;
                select_ln51_61_reg_1677 <= select_ln51_61_fu_1325_p3;
                select_ln51_reg_1542 <= select_ln51_fu_947_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(layer10_out_empty_n, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (layer10_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer12_out_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer12_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_171_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_171 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_1339_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_1339_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i1_fu_232, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_232;
        end if; 
    end process;

    i_fu_1333_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv6_1));
    icmp_ln41_fu_1339_p2 <= "1" when (ap_sig_allocacmp_i1_load = ap_const_lv6_3F) else "0";
    icmp_ln51_39_fu_899_p2 <= "1" when (signed(out_data_9_fu_265_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_40_fu_913_p2 <= "1" when (signed(out_data_11_fu_285_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_41_fu_927_p2 <= "1" when (signed(out_data_1_fu_305_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_42_fu_941_p2 <= "1" when (signed(trunc_ln44_42_fu_325_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_43_fu_955_p2 <= "1" when (signed(trunc_ln44_43_fu_345_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_44_fu_969_p2 <= "1" when (signed(trunc_ln44_44_fu_365_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_45_fu_983_p2 <= "1" when (signed(trunc_ln44_45_fu_385_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_46_fu_997_p2 <= "1" when (signed(trunc_ln44_46_fu_405_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_47_fu_1011_p2 <= "1" when (signed(trunc_ln44_47_fu_425_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_48_fu_1025_p2 <= "1" when (signed(trunc_ln44_48_fu_445_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_49_fu_1039_p2 <= "1" when (signed(trunc_ln44_49_fu_465_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_50_fu_1053_p2 <= "1" when (signed(trunc_ln44_50_fu_485_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_51_fu_1067_p2 <= "1" when (signed(trunc_ln44_51_fu_505_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_52_fu_1081_p2 <= "1" when (signed(trunc_ln44_52_fu_525_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_53_fu_1095_p2 <= "1" when (signed(trunc_ln44_53_fu_545_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_54_fu_1109_p2 <= "1" when (signed(trunc_ln44_54_fu_565_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_55_fu_1123_p2 <= "1" when (signed(trunc_ln44_55_fu_585_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_56_fu_1137_p2 <= "1" when (signed(trunc_ln44_56_fu_605_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_57_fu_1151_p2 <= "1" when (signed(trunc_ln44_57_fu_625_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_58_fu_1165_p2 <= "1" when (signed(trunc_ln44_58_fu_645_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_59_fu_1179_p2 <= "1" when (signed(trunc_ln44_59_fu_665_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_60_fu_1193_p2 <= "1" when (signed(trunc_ln44_60_fu_685_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_61_fu_1207_p2 <= "1" when (signed(trunc_ln44_61_fu_705_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_62_fu_1221_p2 <= "1" when (signed(trunc_ln44_62_fu_725_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_63_fu_1235_p2 <= "1" when (signed(trunc_ln44_63_fu_745_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_64_fu_1249_p2 <= "1" when (signed(trunc_ln44_64_fu_765_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_65_fu_1263_p2 <= "1" when (signed(trunc_ln44_65_fu_785_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_66_fu_1277_p2 <= "1" when (signed(trunc_ln44_66_fu_805_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_67_fu_1291_p2 <= "1" when (signed(trunc_ln44_67_fu_825_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_68_fu_1305_p2 <= "1" when (signed(trunc_ln44_68_fu_845_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_69_fu_1319_p2 <= "1" when (signed(trunc_ln44_69_fu_865_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln51_fu_885_p2 <= "1" when (signed(out_data_fu_257_p1) > signed(ap_const_lv10_0)) else "0";

    layer10_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, layer10_out_empty_n, ap_done_reg, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer10_out_blk_n <= layer10_out_empty_n;
        else 
            layer10_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer10_out_read <= layer10_out_read_local;

    layer10_out_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer10_out_read_local <= ap_const_logic_1;
        else 
            layer10_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer12_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer12_out_blk_n <= layer12_out_full_n;
        else 
            layer12_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer12_out_din <= zext_ln57_fu_1510_p1;
    layer12_out_write <= layer12_out_write_local;

    layer12_out_write_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer12_out_write_local <= ap_const_logic_1;
        else 
            layer12_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1443_p33 <= (((((((((((((((((((((((((((((((select_ln51_61_reg_1677 & zext_ln51_58_fu_1440_p1) & zext_ln51_57_fu_1437_p1) & zext_ln51_56_fu_1434_p1) & zext_ln51_55_fu_1431_p1) & zext_ln51_54_fu_1428_p1) & zext_ln51_53_fu_1425_p1) & zext_ln51_52_fu_1422_p1) & zext_ln51_51_fu_1419_p1) & zext_ln51_50_fu_1416_p1) & zext_ln51_49_fu_1413_p1) & zext_ln51_48_fu_1410_p1) & zext_ln51_47_fu_1407_p1) & zext_ln51_46_fu_1404_p1) & zext_ln51_45_fu_1401_p1) & zext_ln51_44_fu_1398_p1) & zext_ln51_43_fu_1395_p1) & zext_ln51_42_fu_1392_p1) & zext_ln51_41_fu_1389_p1) & zext_ln51_40_fu_1386_p1) & zext_ln51_39_fu_1383_p1) & zext_ln51_38_fu_1380_p1) & zext_ln51_37_fu_1377_p1) & zext_ln51_36_fu_1374_p1) & zext_ln51_35_fu_1371_p1) & zext_ln51_34_fu_1368_p1) & zext_ln51_33_fu_1365_p1) & zext_ln51_fu_1362_p1) & zext_ln45_6_fu_1359_p1) & zext_ln45_5_fu_1356_p1) & zext_ln45_4_fu_1353_p1) & zext_ln45_fu_1350_p1);
    out_data_10_fu_905_p3 <= 
        trunc_ln44_s_fu_275_p4 when (icmp_ln51_39_fu_899_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_11_fu_285_p4 <= layer10_out_dout(29 downto 20);
    out_data_12_fu_919_p3 <= 
        trunc_ln44_70_fu_295_p4 when (icmp_ln51_40_fu_913_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_13_fu_933_p3 <= 
        trunc_ln44_71_fu_315_p4 when (icmp_ln51_41_fu_927_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_1_fu_305_p4 <= layer10_out_dout(39 downto 30);
    out_data_8_fu_891_p3 <= 
        trunc_ln44_100_fu_261_p1 when (icmp_ln51_fu_885_p2(0) = '1') else 
        ap_const_lv9_0;
    out_data_9_fu_265_p4 <= layer10_out_dout(19 downto 10);
    out_data_fu_257_p1 <= layer10_out_dout(10 - 1 downto 0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_35_fu_961_p3 <= 
        trunc_ln44_73_fu_355_p4 when (icmp_ln51_43_fu_955_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_36_fu_975_p3 <= 
        trunc_ln44_74_fu_375_p4 when (icmp_ln51_44_fu_969_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_37_fu_989_p3 <= 
        trunc_ln44_75_fu_395_p4 when (icmp_ln51_45_fu_983_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_38_fu_1003_p3 <= 
        trunc_ln44_76_fu_415_p4 when (icmp_ln51_46_fu_997_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_39_fu_1017_p3 <= 
        trunc_ln44_77_fu_435_p4 when (icmp_ln51_47_fu_1011_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_40_fu_1031_p3 <= 
        trunc_ln44_78_fu_455_p4 when (icmp_ln51_48_fu_1025_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_41_fu_1045_p3 <= 
        trunc_ln44_79_fu_475_p4 when (icmp_ln51_49_fu_1039_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_42_fu_1059_p3 <= 
        trunc_ln44_80_fu_495_p4 when (icmp_ln51_50_fu_1053_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_43_fu_1073_p3 <= 
        trunc_ln44_81_fu_515_p4 when (icmp_ln51_51_fu_1067_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_44_fu_1087_p3 <= 
        trunc_ln44_82_fu_535_p4 when (icmp_ln51_52_fu_1081_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_45_fu_1101_p3 <= 
        trunc_ln44_83_fu_555_p4 when (icmp_ln51_53_fu_1095_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_46_fu_1115_p3 <= 
        trunc_ln44_84_fu_575_p4 when (icmp_ln51_54_fu_1109_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_47_fu_1129_p3 <= 
        trunc_ln44_85_fu_595_p4 when (icmp_ln51_55_fu_1123_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_48_fu_1143_p3 <= 
        trunc_ln44_86_fu_615_p4 when (icmp_ln51_56_fu_1137_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_49_fu_1157_p3 <= 
        trunc_ln44_87_fu_635_p4 when (icmp_ln51_57_fu_1151_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_50_fu_1171_p3 <= 
        trunc_ln44_88_fu_655_p4 when (icmp_ln51_58_fu_1165_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_51_fu_1185_p3 <= 
        trunc_ln44_89_fu_675_p4 when (icmp_ln51_59_fu_1179_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_52_fu_1199_p3 <= 
        trunc_ln44_90_fu_695_p4 when (icmp_ln51_60_fu_1193_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_53_fu_1213_p3 <= 
        trunc_ln44_91_fu_715_p4 when (icmp_ln51_61_fu_1207_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_54_fu_1227_p3 <= 
        trunc_ln44_92_fu_735_p4 when (icmp_ln51_62_fu_1221_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_55_fu_1241_p3 <= 
        trunc_ln44_93_fu_755_p4 when (icmp_ln51_63_fu_1235_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_56_fu_1255_p3 <= 
        trunc_ln44_94_fu_775_p4 when (icmp_ln51_64_fu_1249_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_57_fu_1269_p3 <= 
        trunc_ln44_95_fu_795_p4 when (icmp_ln51_65_fu_1263_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_58_fu_1283_p3 <= 
        trunc_ln44_96_fu_815_p4 when (icmp_ln51_66_fu_1277_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_59_fu_1297_p3 <= 
        trunc_ln44_97_fu_835_p4 when (icmp_ln51_67_fu_1291_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_60_fu_1311_p3 <= 
        trunc_ln44_98_fu_855_p4 when (icmp_ln51_68_fu_1305_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_61_fu_1325_p3 <= 
        trunc_ln_fu_875_p4 when (icmp_ln51_69_fu_1319_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln51_fu_947_p3 <= 
        trunc_ln44_72_fu_335_p4 when (icmp_ln51_42_fu_941_p2(0) = '1') else 
        ap_const_lv9_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_100_fu_261_p1 <= layer10_out_dout(9 - 1 downto 0);
    trunc_ln44_42_fu_325_p4 <= layer10_out_dout(49 downto 40);
    trunc_ln44_43_fu_345_p4 <= layer10_out_dout(59 downto 50);
    trunc_ln44_44_fu_365_p4 <= layer10_out_dout(69 downto 60);
    trunc_ln44_45_fu_385_p4 <= layer10_out_dout(79 downto 70);
    trunc_ln44_46_fu_405_p4 <= layer10_out_dout(89 downto 80);
    trunc_ln44_47_fu_425_p4 <= layer10_out_dout(99 downto 90);
    trunc_ln44_48_fu_445_p4 <= layer10_out_dout(109 downto 100);
    trunc_ln44_49_fu_465_p4 <= layer10_out_dout(119 downto 110);
    trunc_ln44_50_fu_485_p4 <= layer10_out_dout(129 downto 120);
    trunc_ln44_51_fu_505_p4 <= layer10_out_dout(139 downto 130);
    trunc_ln44_52_fu_525_p4 <= layer10_out_dout(149 downto 140);
    trunc_ln44_53_fu_545_p4 <= layer10_out_dout(159 downto 150);
    trunc_ln44_54_fu_565_p4 <= layer10_out_dout(169 downto 160);
    trunc_ln44_55_fu_585_p4 <= layer10_out_dout(179 downto 170);
    trunc_ln44_56_fu_605_p4 <= layer10_out_dout(189 downto 180);
    trunc_ln44_57_fu_625_p4 <= layer10_out_dout(199 downto 190);
    trunc_ln44_58_fu_645_p4 <= layer10_out_dout(209 downto 200);
    trunc_ln44_59_fu_665_p4 <= layer10_out_dout(219 downto 210);
    trunc_ln44_60_fu_685_p4 <= layer10_out_dout(229 downto 220);
    trunc_ln44_61_fu_705_p4 <= layer10_out_dout(239 downto 230);
    trunc_ln44_62_fu_725_p4 <= layer10_out_dout(249 downto 240);
    trunc_ln44_63_fu_745_p4 <= layer10_out_dout(259 downto 250);
    trunc_ln44_64_fu_765_p4 <= layer10_out_dout(269 downto 260);
    trunc_ln44_65_fu_785_p4 <= layer10_out_dout(279 downto 270);
    trunc_ln44_66_fu_805_p4 <= layer10_out_dout(289 downto 280);
    trunc_ln44_67_fu_825_p4 <= layer10_out_dout(299 downto 290);
    trunc_ln44_68_fu_845_p4 <= layer10_out_dout(309 downto 300);
    trunc_ln44_69_fu_865_p4 <= layer10_out_dout(319 downto 310);
    trunc_ln44_70_fu_295_p4 <= layer10_out_dout(28 downto 20);
    trunc_ln44_71_fu_315_p4 <= layer10_out_dout(38 downto 30);
    trunc_ln44_72_fu_335_p4 <= layer10_out_dout(48 downto 40);
    trunc_ln44_73_fu_355_p4 <= layer10_out_dout(58 downto 50);
    trunc_ln44_74_fu_375_p4 <= layer10_out_dout(68 downto 60);
    trunc_ln44_75_fu_395_p4 <= layer10_out_dout(78 downto 70);
    trunc_ln44_76_fu_415_p4 <= layer10_out_dout(88 downto 80);
    trunc_ln44_77_fu_435_p4 <= layer10_out_dout(98 downto 90);
    trunc_ln44_78_fu_455_p4 <= layer10_out_dout(108 downto 100);
    trunc_ln44_79_fu_475_p4 <= layer10_out_dout(118 downto 110);
    trunc_ln44_80_fu_495_p4 <= layer10_out_dout(128 downto 120);
    trunc_ln44_81_fu_515_p4 <= layer10_out_dout(138 downto 130);
    trunc_ln44_82_fu_535_p4 <= layer10_out_dout(148 downto 140);
    trunc_ln44_83_fu_555_p4 <= layer10_out_dout(158 downto 150);
    trunc_ln44_84_fu_575_p4 <= layer10_out_dout(168 downto 160);
    trunc_ln44_85_fu_595_p4 <= layer10_out_dout(178 downto 170);
    trunc_ln44_86_fu_615_p4 <= layer10_out_dout(188 downto 180);
    trunc_ln44_87_fu_635_p4 <= layer10_out_dout(198 downto 190);
    trunc_ln44_88_fu_655_p4 <= layer10_out_dout(208 downto 200);
    trunc_ln44_89_fu_675_p4 <= layer10_out_dout(218 downto 210);
    trunc_ln44_90_fu_695_p4 <= layer10_out_dout(228 downto 220);
    trunc_ln44_91_fu_715_p4 <= layer10_out_dout(238 downto 230);
    trunc_ln44_92_fu_735_p4 <= layer10_out_dout(248 downto 240);
    trunc_ln44_93_fu_755_p4 <= layer10_out_dout(258 downto 250);
    trunc_ln44_94_fu_775_p4 <= layer10_out_dout(268 downto 260);
    trunc_ln44_95_fu_795_p4 <= layer10_out_dout(278 downto 270);
    trunc_ln44_96_fu_815_p4 <= layer10_out_dout(288 downto 280);
    trunc_ln44_97_fu_835_p4 <= layer10_out_dout(298 downto 290);
    trunc_ln44_98_fu_855_p4 <= layer10_out_dout(308 downto 300);
    trunc_ln44_s_fu_275_p4 <= layer10_out_dout(18 downto 10);
    trunc_ln_fu_875_p4 <= layer10_out_dout(318 downto 310);
    zext_ln45_4_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_10_reg_1527),10));
    zext_ln45_5_fu_1356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_12_reg_1532),10));
    zext_ln45_6_fu_1359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_13_reg_1537),10));
    zext_ln45_fu_1350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_8_reg_1522),10));
    zext_ln51_33_fu_1365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_35_reg_1547),10));
    zext_ln51_34_fu_1368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_36_reg_1552),10));
    zext_ln51_35_fu_1371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_37_reg_1557),10));
    zext_ln51_36_fu_1374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_38_reg_1562),10));
    zext_ln51_37_fu_1377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_39_reg_1567),10));
    zext_ln51_38_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_40_reg_1572),10));
    zext_ln51_39_fu_1383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_41_reg_1577),10));
    zext_ln51_40_fu_1386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_42_reg_1582),10));
    zext_ln51_41_fu_1389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_43_reg_1587),10));
    zext_ln51_42_fu_1392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_44_reg_1592),10));
    zext_ln51_43_fu_1395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_45_reg_1597),10));
    zext_ln51_44_fu_1398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_46_reg_1602),10));
    zext_ln51_45_fu_1401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_47_reg_1607),10));
    zext_ln51_46_fu_1404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_48_reg_1612),10));
    zext_ln51_47_fu_1407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_49_reg_1617),10));
    zext_ln51_48_fu_1410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_50_reg_1622),10));
    zext_ln51_49_fu_1413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_51_reg_1627),10));
    zext_ln51_50_fu_1416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_52_reg_1632),10));
    zext_ln51_51_fu_1419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_53_reg_1637),10));
    zext_ln51_52_fu_1422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_54_reg_1642),10));
    zext_ln51_53_fu_1425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_55_reg_1647),10));
    zext_ln51_54_fu_1428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_56_reg_1652),10));
    zext_ln51_55_fu_1431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_57_reg_1657),10));
    zext_ln51_56_fu_1434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_58_reg_1662),10));
    zext_ln51_57_fu_1437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_59_reg_1667),10));
    zext_ln51_58_fu_1440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_60_reg_1672),10));
    zext_ln51_fu_1362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_1542),10));
    zext_ln57_fu_1510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1443_p33),320));
end behav;
