// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer22_out_dout,
        layer22_out_num_data_valid,
        layer22_out_fifo_cap,
        layer22_out_empty_n,
        layer22_out_read,
        layer10_out_din,
        layer10_out_num_data_valid,
        layer10_out_fifo_cap,
        layer10_out_full_n,
        layer10_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [159:0] layer22_out_dout;
input  [7:0] layer22_out_num_data_valid;
input  [7:0] layer22_out_fifo_cap;
input   layer22_out_empty_n;
output   layer22_out_read;
output  [319:0] layer10_out_din;
input  [6:0] layer10_out_num_data_valid;
input  [6:0] layer10_out_fifo_cap;
input   layer10_out_full_n;
output   layer10_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer10_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer22_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln79_fu_860_p2;
wire   [9:0] trunc_ln87_fu_872_p1;
reg   [9:0] trunc_ln87_reg_1057;
reg    ap_block_state2;
reg   [9:0] trunc_ln87_s_reg_1062;
reg   [9:0] trunc_ln87_1_reg_1067;
reg   [9:0] trunc_ln87_2_reg_1072;
reg   [9:0] trunc_ln87_3_reg_1077;
reg   [9:0] trunc_ln87_4_reg_1082;
reg   [9:0] trunc_ln87_5_reg_1087;
reg   [9:0] trunc_ln87_6_reg_1092;
reg   [9:0] trunc_ln87_7_reg_1097;
reg   [9:0] trunc_ln87_8_reg_1102;
reg   [9:0] trunc_ln87_9_reg_1107;
reg   [9:0] trunc_ln87_10_reg_1112;
reg   [9:0] trunc_ln87_11_reg_1117;
reg   [9:0] trunc_ln87_12_reg_1122;
reg   [9:0] trunc_ln87_13_reg_1127;
reg   [9:0] trunc_ln87_14_reg_1132;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready;
wire   [319:0] grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg;
reg    ap_block_state2_ignore_call19;
wire    ap_CS_fsm_state3;
reg   [6:0] indvar_flatten_fu_458;
wire   [6:0] add_ln79_fu_866_p2;
reg    ap_block_state1;
reg    layer22_out_read_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_458 = 7'd0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready),
    .p_read(trunc_ln87_reg_1057),
    .p_read1(trunc_ln87_s_reg_1062),
    .p_read2(trunc_ln87_1_reg_1067),
    .p_read3(trunc_ln87_2_reg_1072),
    .p_read4(trunc_ln87_3_reg_1077),
    .p_read5(trunc_ln87_4_reg_1082),
    .p_read6(trunc_ln87_5_reg_1087),
    .p_read7(trunc_ln87_6_reg_1092),
    .p_read8(trunc_ln87_7_reg_1097),
    .p_read9(trunc_ln87_8_reg_1102),
    .p_read10(trunc_ln87_9_reg_1107),
    .p_read11(trunc_ln87_10_reg_1112),
    .p_read12(trunc_ln87_11_reg_1117),
    .p_read13(trunc_ln87_12_reg_1122),
    .p_read14(trunc_ln87_13_reg_1127),
    .p_read15(trunc_ln87_14_reg_1132),
    .layer10_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din),
    .layer10_out_num_data_valid(7'd0),
    .layer10_out_fifo_cap(7'd0),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call19) & (icmp_ln79_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_458 <= 7'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_458 <= add_ln79_fu_866_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln87_10_reg_1112 <= {{layer22_out_dout[119:110]}};
        trunc_ln87_11_reg_1117 <= {{layer22_out_dout[129:120]}};
        trunc_ln87_12_reg_1122 <= {{layer22_out_dout[139:130]}};
        trunc_ln87_13_reg_1127 <= {{layer22_out_dout[149:140]}};
        trunc_ln87_14_reg_1132 <= {{layer22_out_dout[159:150]}};
        trunc_ln87_1_reg_1067 <= {{layer22_out_dout[29:20]}};
        trunc_ln87_2_reg_1072 <= {{layer22_out_dout[39:30]}};
        trunc_ln87_3_reg_1077 <= {{layer22_out_dout[49:40]}};
        trunc_ln87_4_reg_1082 <= {{layer22_out_dout[59:50]}};
        trunc_ln87_5_reg_1087 <= {{layer22_out_dout[69:60]}};
        trunc_ln87_6_reg_1092 <= {{layer22_out_dout[79:70]}};
        trunc_ln87_7_reg_1097 <= {{layer22_out_dout[89:80]}};
        trunc_ln87_8_reg_1102 <= {{layer22_out_dout[99:90]}};
        trunc_ln87_9_reg_1107 <= {{layer22_out_dout[109:100]}};
        trunc_ln87_reg_1057 <= trunc_ln87_fu_872_p1;
        trunc_ln87_s_reg_1062 <= {{layer22_out_dout[19:10]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer10_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_write;
    end else begin
        layer10_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer22_out_blk_n = layer22_out_empty_n;
    end else begin
        layer22_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer22_out_read_local = 1'b1;
    end else begin
        layer22_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln79_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln79_fu_866_p2 = (indvar_flatten_fu_458 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln79_fu_860_p2 == 1'd0) & (layer22_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call19 = ((icmp_ln79_fu_860_p2 == 1'd0) & (layer22_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_ap_start_reg;

assign icmp_ln79_fu_860_p2 = ((indvar_flatten_fu_458 == 7'd100) ? 1'b1 : 1'b0);

assign layer10_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_10_4_5_3_0_32u_config10_s_fu_468_layer10_out_din;

assign layer22_out_read = layer22_out_read_local;

assign start_out = real_start;

assign trunc_ln87_fu_872_p1 = layer22_out_dout[9:0];

endmodule //myproject_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_s
