// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_empty_n,
        layer6_out_read,
        layer8_out_din,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_full_n,
        layer8_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [159:0] layer6_out_dout;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [159:0] layer8_out_din;
input  [8:0] layer8_out_num_data_valid;
input  [8:0] layer8_out_fifo_cap;
input   layer8_out_full_n;
output   layer8_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_699_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer8_out_blk_n;
wire   [8:0] out_data_14_fu_475_p3;
reg   [8:0] out_data_14_reg_802;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] out_data_16_fu_489_p3;
reg   [8:0] out_data_16_reg_807;
wire   [8:0] out_data_17_fu_503_p3;
reg   [8:0] out_data_17_reg_812;
wire   [8:0] out_data_18_fu_517_p3;
reg   [8:0] out_data_18_reg_817;
wire   [8:0] select_ln51_fu_531_p3;
reg   [8:0] select_ln51_reg_822;
wire   [8:0] select_ln51_62_fu_545_p3;
reg   [8:0] select_ln51_62_reg_827;
wire   [8:0] select_ln51_63_fu_559_p3;
reg   [8:0] select_ln51_63_reg_832;
wire   [8:0] select_ln51_64_fu_573_p3;
reg   [8:0] select_ln51_64_reg_837;
wire   [8:0] select_ln51_65_fu_587_p3;
reg   [8:0] select_ln51_65_reg_842;
wire   [8:0] select_ln51_66_fu_601_p3;
reg   [8:0] select_ln51_66_reg_847;
wire   [8:0] select_ln51_67_fu_615_p3;
reg   [8:0] select_ln51_67_reg_852;
wire   [8:0] select_ln51_68_fu_629_p3;
reg   [8:0] select_ln51_68_reg_857;
wire   [8:0] select_ln51_69_fu_643_p3;
reg   [8:0] select_ln51_69_reg_862;
wire   [8:0] select_ln51_70_fu_657_p3;
reg   [8:0] select_ln51_70_reg_867;
wire   [8:0] select_ln51_71_fu_671_p3;
reg   [8:0] select_ln51_71_reg_872;
wire   [8:0] select_ln51_72_fu_685_p3;
reg   [8:0] select_ln51_72_reg_877;
reg   [7:0] i1_fu_136;
wire   [7:0] i_fu_693_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i1_load;
reg    layer6_out_read_local;
wire   [159:0] zext_ln57_fu_790_p1;
reg    ap_block_pp0_stage0_01001;
reg    layer8_out_write_local;
wire   [9:0] out_data_fu_161_p1;
wire   [0:0] icmp_ln51_fu_469_p2;
wire   [8:0] trunc_ln44_114_fu_165_p1;
wire   [9:0] out_data_15_fu_169_p4;
wire   [0:0] icmp_ln51_70_fu_483_p2;
wire   [8:0] trunc_ln44_s_fu_179_p4;
wire   [9:0] out_data_2_fu_189_p4;
wire   [0:0] icmp_ln51_71_fu_497_p2;
wire   [8:0] trunc_ln44_99_fu_199_p4;
wire   [9:0] out_data_3_fu_209_p4;
wire   [0:0] icmp_ln51_72_fu_511_p2;
wire   [8:0] trunc_ln44_100_fu_219_p4;
wire   [9:0] trunc_ln44_73_fu_229_p4;
wire   [0:0] icmp_ln51_73_fu_525_p2;
wire   [8:0] trunc_ln44_101_fu_239_p4;
wire   [9:0] trunc_ln44_74_fu_249_p4;
wire   [0:0] icmp_ln51_74_fu_539_p2;
wire   [8:0] trunc_ln44_102_fu_259_p4;
wire   [9:0] trunc_ln44_75_fu_269_p4;
wire   [0:0] icmp_ln51_75_fu_553_p2;
wire   [8:0] trunc_ln44_103_fu_279_p4;
wire   [9:0] trunc_ln44_76_fu_289_p4;
wire   [0:0] icmp_ln51_76_fu_567_p2;
wire   [8:0] trunc_ln44_104_fu_299_p4;
wire   [9:0] trunc_ln44_77_fu_309_p4;
wire   [0:0] icmp_ln51_77_fu_581_p2;
wire   [8:0] trunc_ln44_105_fu_319_p4;
wire   [9:0] trunc_ln44_78_fu_329_p4;
wire   [0:0] icmp_ln51_78_fu_595_p2;
wire   [8:0] trunc_ln44_106_fu_339_p4;
wire   [9:0] trunc_ln44_79_fu_349_p4;
wire   [0:0] icmp_ln51_79_fu_609_p2;
wire   [8:0] trunc_ln44_107_fu_359_p4;
wire   [9:0] trunc_ln44_80_fu_369_p4;
wire   [0:0] icmp_ln51_80_fu_623_p2;
wire   [8:0] trunc_ln44_108_fu_379_p4;
wire   [9:0] trunc_ln44_81_fu_389_p4;
wire   [0:0] icmp_ln51_81_fu_637_p2;
wire   [8:0] trunc_ln44_109_fu_399_p4;
wire   [9:0] trunc_ln44_82_fu_409_p4;
wire   [0:0] icmp_ln51_82_fu_651_p2;
wire   [8:0] trunc_ln44_110_fu_419_p4;
wire   [9:0] trunc_ln44_83_fu_429_p4;
wire   [0:0] icmp_ln51_83_fu_665_p2;
wire   [8:0] trunc_ln44_111_fu_439_p4;
wire   [9:0] trunc_ln44_84_fu_449_p4;
wire   [0:0] icmp_ln51_84_fu_679_p2;
wire   [8:0] trunc_ln_fu_459_p4;
wire   [9:0] zext_ln51_68_fu_752_p1;
wire   [9:0] zext_ln51_67_fu_749_p1;
wire   [9:0] zext_ln51_66_fu_746_p1;
wire   [9:0] zext_ln51_65_fu_743_p1;
wire   [9:0] zext_ln51_64_fu_740_p1;
wire   [9:0] zext_ln51_63_fu_737_p1;
wire   [9:0] zext_ln51_62_fu_734_p1;
wire   [9:0] zext_ln51_61_fu_731_p1;
wire   [9:0] zext_ln51_60_fu_728_p1;
wire   [9:0] zext_ln51_59_fu_725_p1;
wire   [9:0] zext_ln51_fu_722_p1;
wire   [9:0] zext_ln45_9_fu_719_p1;
wire   [9:0] zext_ln45_8_fu_716_p1;
wire   [9:0] zext_ln45_7_fu_713_p1;
wire   [9:0] zext_ln45_fu_710_p1;
wire   [158:0] or_ln57_s_fu_755_p17;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_139;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i1_fu_136 = 8'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_139)) begin
        i1_fu_136 <= i_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_14_reg_802 <= out_data_14_fu_475_p3;
        out_data_16_reg_807 <= out_data_16_fu_489_p3;
        out_data_17_reg_812 <= out_data_17_fu_503_p3;
        out_data_18_reg_817 <= out_data_18_fu_517_p3;
        select_ln51_62_reg_827 <= select_ln51_62_fu_545_p3;
        select_ln51_63_reg_832 <= select_ln51_63_fu_559_p3;
        select_ln51_64_reg_837 <= select_ln51_64_fu_573_p3;
        select_ln51_65_reg_842 <= select_ln51_65_fu_587_p3;
        select_ln51_66_reg_847 <= select_ln51_66_fu_601_p3;
        select_ln51_67_reg_852 <= select_ln51_67_fu_615_p3;
        select_ln51_68_reg_857 <= select_ln51_68_fu_629_p3;
        select_ln51_69_reg_862 <= select_ln51_69_fu_643_p3;
        select_ln51_70_reg_867 <= select_ln51_70_fu_657_p3;
        select_ln51_71_reg_872 <= select_ln51_71_fu_671_p3;
        select_ln51_72_reg_877 <= select_ln51_72_fu_685_p3;
        select_ln51_reg_822 <= select_ln51_fu_531_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_699_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read_local = 1'b1;
    end else begin
        layer6_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_write_local = 1'b1;
    end else begin
        layer8_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (layer6_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer8_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_139 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_fu_693_p2 = (ap_sig_allocacmp_i1_load + 8'd1);

assign icmp_ln41_fu_699_p2 = ((ap_sig_allocacmp_i1_load == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln51_70_fu_483_p2 = (($signed(out_data_15_fu_169_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_71_fu_497_p2 = (($signed(out_data_2_fu_189_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_72_fu_511_p2 = (($signed(out_data_3_fu_209_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_73_fu_525_p2 = (($signed(trunc_ln44_73_fu_229_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_74_fu_539_p2 = (($signed(trunc_ln44_74_fu_249_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_75_fu_553_p2 = (($signed(trunc_ln44_75_fu_269_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_76_fu_567_p2 = (($signed(trunc_ln44_76_fu_289_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_77_fu_581_p2 = (($signed(trunc_ln44_77_fu_309_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_78_fu_595_p2 = (($signed(trunc_ln44_78_fu_329_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_79_fu_609_p2 = (($signed(trunc_ln44_79_fu_349_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_80_fu_623_p2 = (($signed(trunc_ln44_80_fu_369_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_81_fu_637_p2 = (($signed(trunc_ln44_81_fu_389_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_82_fu_651_p2 = (($signed(trunc_ln44_82_fu_409_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_83_fu_665_p2 = (($signed(trunc_ln44_83_fu_429_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_84_fu_679_p2 = (($signed(trunc_ln44_84_fu_449_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_469_p2 = (($signed(out_data_fu_161_p1) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign layer6_out_read = layer6_out_read_local;

assign layer8_out_din = zext_ln57_fu_790_p1;

assign layer8_out_write = layer8_out_write_local;

assign or_ln57_s_fu_755_p17 = {{{{{{{{{{{{{{{{select_ln51_72_reg_877}, {zext_ln51_68_fu_752_p1}}, {zext_ln51_67_fu_749_p1}}, {zext_ln51_66_fu_746_p1}}, {zext_ln51_65_fu_743_p1}}, {zext_ln51_64_fu_740_p1}}, {zext_ln51_63_fu_737_p1}}, {zext_ln51_62_fu_734_p1}}, {zext_ln51_61_fu_731_p1}}, {zext_ln51_60_fu_728_p1}}, {zext_ln51_59_fu_725_p1}}, {zext_ln51_fu_722_p1}}, {zext_ln45_9_fu_719_p1}}, {zext_ln45_8_fu_716_p1}}, {zext_ln45_7_fu_713_p1}}, {zext_ln45_fu_710_p1}};

assign out_data_14_fu_475_p3 = ((icmp_ln51_fu_469_p2[0:0] == 1'b1) ? trunc_ln44_114_fu_165_p1 : 9'd0);

assign out_data_15_fu_169_p4 = {{layer6_out_dout[19:10]}};

assign out_data_16_fu_489_p3 = ((icmp_ln51_70_fu_483_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_179_p4 : 9'd0);

assign out_data_17_fu_503_p3 = ((icmp_ln51_71_fu_497_p2[0:0] == 1'b1) ? trunc_ln44_99_fu_199_p4 : 9'd0);

assign out_data_18_fu_517_p3 = ((icmp_ln51_72_fu_511_p2[0:0] == 1'b1) ? trunc_ln44_100_fu_219_p4 : 9'd0);

assign out_data_2_fu_189_p4 = {{layer6_out_dout[29:20]}};

assign out_data_3_fu_209_p4 = {{layer6_out_dout[39:30]}};

assign out_data_fu_161_p1 = layer6_out_dout[9:0];

assign select_ln51_62_fu_545_p3 = ((icmp_ln51_74_fu_539_p2[0:0] == 1'b1) ? trunc_ln44_102_fu_259_p4 : 9'd0);

assign select_ln51_63_fu_559_p3 = ((icmp_ln51_75_fu_553_p2[0:0] == 1'b1) ? trunc_ln44_103_fu_279_p4 : 9'd0);

assign select_ln51_64_fu_573_p3 = ((icmp_ln51_76_fu_567_p2[0:0] == 1'b1) ? trunc_ln44_104_fu_299_p4 : 9'd0);

assign select_ln51_65_fu_587_p3 = ((icmp_ln51_77_fu_581_p2[0:0] == 1'b1) ? trunc_ln44_105_fu_319_p4 : 9'd0);

assign select_ln51_66_fu_601_p3 = ((icmp_ln51_78_fu_595_p2[0:0] == 1'b1) ? trunc_ln44_106_fu_339_p4 : 9'd0);

assign select_ln51_67_fu_615_p3 = ((icmp_ln51_79_fu_609_p2[0:0] == 1'b1) ? trunc_ln44_107_fu_359_p4 : 9'd0);

assign select_ln51_68_fu_629_p3 = ((icmp_ln51_80_fu_623_p2[0:0] == 1'b1) ? trunc_ln44_108_fu_379_p4 : 9'd0);

assign select_ln51_69_fu_643_p3 = ((icmp_ln51_81_fu_637_p2[0:0] == 1'b1) ? trunc_ln44_109_fu_399_p4 : 9'd0);

assign select_ln51_70_fu_657_p3 = ((icmp_ln51_82_fu_651_p2[0:0] == 1'b1) ? trunc_ln44_110_fu_419_p4 : 9'd0);

assign select_ln51_71_fu_671_p3 = ((icmp_ln51_83_fu_665_p2[0:0] == 1'b1) ? trunc_ln44_111_fu_439_p4 : 9'd0);

assign select_ln51_72_fu_685_p3 = ((icmp_ln51_84_fu_679_p2[0:0] == 1'b1) ? trunc_ln_fu_459_p4 : 9'd0);

assign select_ln51_fu_531_p3 = ((icmp_ln51_73_fu_525_p2[0:0] == 1'b1) ? trunc_ln44_101_fu_239_p4 : 9'd0);

assign start_out = real_start;

assign trunc_ln44_100_fu_219_p4 = {{layer6_out_dout[38:30]}};

assign trunc_ln44_101_fu_239_p4 = {{layer6_out_dout[48:40]}};

assign trunc_ln44_102_fu_259_p4 = {{layer6_out_dout[58:50]}};

assign trunc_ln44_103_fu_279_p4 = {{layer6_out_dout[68:60]}};

assign trunc_ln44_104_fu_299_p4 = {{layer6_out_dout[78:70]}};

assign trunc_ln44_105_fu_319_p4 = {{layer6_out_dout[88:80]}};

assign trunc_ln44_106_fu_339_p4 = {{layer6_out_dout[98:90]}};

assign trunc_ln44_107_fu_359_p4 = {{layer6_out_dout[108:100]}};

assign trunc_ln44_108_fu_379_p4 = {{layer6_out_dout[118:110]}};

assign trunc_ln44_109_fu_399_p4 = {{layer6_out_dout[128:120]}};

assign trunc_ln44_110_fu_419_p4 = {{layer6_out_dout[138:130]}};

assign trunc_ln44_111_fu_439_p4 = {{layer6_out_dout[148:140]}};

assign trunc_ln44_114_fu_165_p1 = layer6_out_dout[8:0];

assign trunc_ln44_73_fu_229_p4 = {{layer6_out_dout[49:40]}};

assign trunc_ln44_74_fu_249_p4 = {{layer6_out_dout[59:50]}};

assign trunc_ln44_75_fu_269_p4 = {{layer6_out_dout[69:60]}};

assign trunc_ln44_76_fu_289_p4 = {{layer6_out_dout[79:70]}};

assign trunc_ln44_77_fu_309_p4 = {{layer6_out_dout[89:80]}};

assign trunc_ln44_78_fu_329_p4 = {{layer6_out_dout[99:90]}};

assign trunc_ln44_79_fu_349_p4 = {{layer6_out_dout[109:100]}};

assign trunc_ln44_80_fu_369_p4 = {{layer6_out_dout[119:110]}};

assign trunc_ln44_81_fu_389_p4 = {{layer6_out_dout[129:120]}};

assign trunc_ln44_82_fu_409_p4 = {{layer6_out_dout[139:130]}};

assign trunc_ln44_83_fu_429_p4 = {{layer6_out_dout[149:140]}};

assign trunc_ln44_84_fu_449_p4 = {{layer6_out_dout[159:150]}};

assign trunc_ln44_99_fu_199_p4 = {{layer6_out_dout[28:20]}};

assign trunc_ln44_s_fu_179_p4 = {{layer6_out_dout[18:10]}};

assign trunc_ln_fu_459_p4 = {{layer6_out_dout[158:150]}};

assign zext_ln45_7_fu_713_p1 = out_data_16_reg_807;

assign zext_ln45_8_fu_716_p1 = out_data_17_reg_812;

assign zext_ln45_9_fu_719_p1 = out_data_18_reg_817;

assign zext_ln45_fu_710_p1 = out_data_14_reg_802;

assign zext_ln51_59_fu_725_p1 = select_ln51_62_reg_827;

assign zext_ln51_60_fu_728_p1 = select_ln51_63_reg_832;

assign zext_ln51_61_fu_731_p1 = select_ln51_64_reg_837;

assign zext_ln51_62_fu_734_p1 = select_ln51_65_reg_842;

assign zext_ln51_63_fu_737_p1 = select_ln51_66_reg_847;

assign zext_ln51_64_fu_740_p1 = select_ln51_67_reg_852;

assign zext_ln51_65_fu_743_p1 = select_ln51_68_reg_857;

assign zext_ln51_66_fu_746_p1 = select_ln51_69_reg_862;

assign zext_ln51_67_fu_749_p1 = select_ln51_70_reg_867;

assign zext_ln51_68_fu_752_p1 = select_ln51_71_reg_872;

assign zext_ln51_fu_722_p1 = select_ln51_reg_822;

assign zext_ln57_fu_790_p1 = or_ln57_s_fu_755_p17;

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_s
