// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer15_out_dout,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_empty_n,
        layer15_out_read,
        layer17_out_din,
        layer17_out_num_data_valid,
        layer17_out_fifo_cap,
        layer17_out_full_n,
        layer17_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [319:0] layer15_out_dout;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;
input   layer15_out_empty_n;
output   layer15_out_read;
output  [319:0] layer17_out_din;
input  [1:0] layer17_out_num_data_valid;
input  [1:0] layer17_out_fifo_cap;
input   layer17_out_full_n;
output   layer17_out_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer15_out_blk_n;
reg    layer17_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [8:0] select_ln51_fu_861_p3;
reg   [8:0] select_ln51_reg_1468;
reg    ap_block_state1;
wire   [8:0] select_ln51_4_fu_875_p3;
reg   [8:0] select_ln51_4_reg_1473;
wire   [8:0] select_ln51_5_fu_889_p3;
reg   [8:0] select_ln51_5_reg_1478;
wire   [8:0] select_ln51_6_fu_903_p3;
reg   [8:0] select_ln51_6_reg_1483;
wire   [8:0] select_ln51_7_fu_917_p3;
reg   [8:0] select_ln51_7_reg_1488;
wire   [8:0] select_ln51_8_fu_931_p3;
reg   [8:0] select_ln51_8_reg_1493;
wire   [8:0] select_ln51_9_fu_945_p3;
reg   [8:0] select_ln51_9_reg_1498;
wire   [8:0] select_ln51_10_fu_959_p3;
reg   [8:0] select_ln51_10_reg_1503;
wire   [8:0] select_ln51_11_fu_973_p3;
reg   [8:0] select_ln51_11_reg_1508;
wire   [8:0] select_ln51_12_fu_987_p3;
reg   [8:0] select_ln51_12_reg_1513;
wire   [8:0] select_ln51_13_fu_1001_p3;
reg   [8:0] select_ln51_13_reg_1518;
wire   [8:0] select_ln51_14_fu_1015_p3;
reg   [8:0] select_ln51_14_reg_1523;
wire   [8:0] select_ln51_15_fu_1029_p3;
reg   [8:0] select_ln51_15_reg_1528;
wire   [8:0] select_ln51_16_fu_1043_p3;
reg   [8:0] select_ln51_16_reg_1533;
wire   [8:0] select_ln51_17_fu_1057_p3;
reg   [8:0] select_ln51_17_reg_1538;
wire   [8:0] select_ln51_18_fu_1071_p3;
reg   [8:0] select_ln51_18_reg_1543;
wire   [8:0] select_ln51_19_fu_1085_p3;
reg   [8:0] select_ln51_19_reg_1548;
wire   [8:0] select_ln51_20_fu_1099_p3;
reg   [8:0] select_ln51_20_reg_1553;
wire   [8:0] select_ln51_21_fu_1113_p3;
reg   [8:0] select_ln51_21_reg_1558;
wire   [8:0] select_ln51_22_fu_1127_p3;
reg   [8:0] select_ln51_22_reg_1563;
wire   [8:0] select_ln51_23_fu_1141_p3;
reg   [8:0] select_ln51_23_reg_1568;
wire   [8:0] select_ln51_24_fu_1155_p3;
reg   [8:0] select_ln51_24_reg_1573;
wire   [8:0] select_ln51_25_fu_1169_p3;
reg   [8:0] select_ln51_25_reg_1578;
wire   [8:0] select_ln51_26_fu_1183_p3;
reg   [8:0] select_ln51_26_reg_1583;
wire   [8:0] select_ln51_27_fu_1197_p3;
reg   [8:0] select_ln51_27_reg_1588;
wire   [8:0] select_ln51_28_fu_1211_p3;
reg   [8:0] select_ln51_28_reg_1593;
wire   [8:0] select_ln51_29_fu_1225_p3;
reg   [8:0] select_ln51_29_reg_1598;
wire   [8:0] select_ln51_30_fu_1239_p3;
reg   [8:0] select_ln51_30_reg_1603;
wire   [8:0] select_ln51_31_fu_1253_p3;
reg   [8:0] select_ln51_31_reg_1608;
wire   [8:0] select_ln51_32_fu_1267_p3;
reg   [8:0] select_ln51_32_reg_1613;
wire   [8:0] select_ln51_33_fu_1281_p3;
reg   [8:0] select_ln51_33_reg_1618;
wire   [8:0] select_ln51_34_fu_1295_p3;
reg   [8:0] select_ln51_34_reg_1623;
reg    layer15_out_read_local;
wire   [319:0] zext_ln57_fu_1463_p1;
reg    layer17_out_write_local;
wire   [9:0] trunc_ln44_fu_227_p1;
wire   [0:0] icmp_ln51_fu_855_p2;
wire   [8:0] trunc_ln44_69_fu_231_p1;
wire   [9:0] trunc_ln44_8_fu_235_p4;
wire   [0:0] icmp_ln51_8_fu_869_p2;
wire   [8:0] trunc_ln44_s_fu_245_p4;
wire   [9:0] trunc_ln44_9_fu_255_p4;
wire   [0:0] icmp_ln51_9_fu_883_p2;
wire   [8:0] trunc_ln44_1_fu_265_p4;
wire   [9:0] trunc_ln44_2_fu_275_p4;
wire   [0:0] icmp_ln51_10_fu_897_p2;
wire   [8:0] trunc_ln44_3_fu_285_p4;
wire   [9:0] trunc_ln44_4_fu_295_p4;
wire   [0:0] icmp_ln51_11_fu_911_p2;
wire   [8:0] trunc_ln44_5_fu_305_p4;
wire   [9:0] trunc_ln44_6_fu_315_p4;
wire   [0:0] icmp_ln51_12_fu_925_p2;
wire   [8:0] trunc_ln44_7_fu_325_p4;
wire   [9:0] trunc_ln44_10_fu_335_p4;
wire   [0:0] icmp_ln51_13_fu_939_p2;
wire   [8:0] trunc_ln44_11_fu_345_p4;
wire   [9:0] trunc_ln44_12_fu_355_p4;
wire   [0:0] icmp_ln51_14_fu_953_p2;
wire   [8:0] trunc_ln44_13_fu_365_p4;
wire   [9:0] trunc_ln44_14_fu_375_p4;
wire   [0:0] icmp_ln51_15_fu_967_p2;
wire   [8:0] trunc_ln44_15_fu_385_p4;
wire   [9:0] trunc_ln44_16_fu_395_p4;
wire   [0:0] icmp_ln51_16_fu_981_p2;
wire   [8:0] trunc_ln44_39_fu_405_p4;
wire   [9:0] trunc_ln44_17_fu_415_p4;
wire   [0:0] icmp_ln51_17_fu_995_p2;
wire   [8:0] trunc_ln44_40_fu_425_p4;
wire   [9:0] trunc_ln44_18_fu_435_p4;
wire   [0:0] icmp_ln51_18_fu_1009_p2;
wire   [8:0] trunc_ln44_41_fu_445_p4;
wire   [9:0] trunc_ln44_19_fu_455_p4;
wire   [0:0] icmp_ln51_19_fu_1023_p2;
wire   [8:0] trunc_ln44_42_fu_465_p4;
wire   [9:0] trunc_ln44_20_fu_475_p4;
wire   [0:0] icmp_ln51_20_fu_1037_p2;
wire   [8:0] trunc_ln44_43_fu_485_p4;
wire   [9:0] trunc_ln44_21_fu_495_p4;
wire   [0:0] icmp_ln51_21_fu_1051_p2;
wire   [8:0] trunc_ln44_44_fu_505_p4;
wire   [9:0] trunc_ln44_22_fu_515_p4;
wire   [0:0] icmp_ln51_22_fu_1065_p2;
wire   [8:0] trunc_ln44_45_fu_525_p4;
wire   [9:0] trunc_ln44_23_fu_535_p4;
wire   [0:0] icmp_ln51_23_fu_1079_p2;
wire   [8:0] trunc_ln44_46_fu_545_p4;
wire   [9:0] trunc_ln44_24_fu_555_p4;
wire   [0:0] icmp_ln51_24_fu_1093_p2;
wire   [8:0] trunc_ln44_47_fu_565_p4;
wire   [9:0] trunc_ln44_25_fu_575_p4;
wire   [0:0] icmp_ln51_25_fu_1107_p2;
wire   [8:0] trunc_ln44_48_fu_585_p4;
wire   [9:0] trunc_ln44_26_fu_595_p4;
wire   [0:0] icmp_ln51_26_fu_1121_p2;
wire   [8:0] trunc_ln44_49_fu_605_p4;
wire   [9:0] trunc_ln44_27_fu_615_p4;
wire   [0:0] icmp_ln51_27_fu_1135_p2;
wire   [8:0] trunc_ln44_50_fu_625_p4;
wire   [9:0] trunc_ln44_28_fu_635_p4;
wire   [0:0] icmp_ln51_28_fu_1149_p2;
wire   [8:0] trunc_ln44_51_fu_645_p4;
wire   [9:0] trunc_ln44_29_fu_655_p4;
wire   [0:0] icmp_ln51_29_fu_1163_p2;
wire   [8:0] trunc_ln44_52_fu_665_p4;
wire   [9:0] trunc_ln44_30_fu_675_p4;
wire   [0:0] icmp_ln51_30_fu_1177_p2;
wire   [8:0] trunc_ln44_53_fu_685_p4;
wire   [9:0] trunc_ln44_31_fu_695_p4;
wire   [0:0] icmp_ln51_31_fu_1191_p2;
wire   [8:0] trunc_ln44_54_fu_705_p4;
wire   [9:0] trunc_ln44_32_fu_715_p4;
wire   [0:0] icmp_ln51_32_fu_1205_p2;
wire   [8:0] trunc_ln44_55_fu_725_p4;
wire   [9:0] trunc_ln44_33_fu_735_p4;
wire   [0:0] icmp_ln51_33_fu_1219_p2;
wire   [8:0] trunc_ln44_56_fu_745_p4;
wire   [9:0] trunc_ln44_34_fu_755_p4;
wire   [0:0] icmp_ln51_34_fu_1233_p2;
wire   [8:0] trunc_ln44_57_fu_765_p4;
wire   [9:0] trunc_ln44_35_fu_775_p4;
wire   [0:0] icmp_ln51_35_fu_1247_p2;
wire   [8:0] trunc_ln44_58_fu_785_p4;
wire   [9:0] trunc_ln44_36_fu_795_p4;
wire   [0:0] icmp_ln51_36_fu_1261_p2;
wire   [8:0] trunc_ln44_59_fu_805_p4;
wire   [9:0] trunc_ln44_37_fu_815_p4;
wire   [0:0] icmp_ln51_37_fu_1275_p2;
wire   [8:0] trunc_ln44_60_fu_825_p4;
wire   [9:0] trunc_ln44_38_fu_835_p4;
wire   [0:0] icmp_ln51_38_fu_1289_p2;
wire   [8:0] trunc_ln1_fu_845_p4;
wire   [9:0] zext_ln51_32_fu_1393_p1;
wire   [9:0] zext_ln51_31_fu_1390_p1;
wire   [9:0] zext_ln51_30_fu_1387_p1;
wire   [9:0] zext_ln51_29_fu_1384_p1;
wire   [9:0] zext_ln51_28_fu_1381_p1;
wire   [9:0] zext_ln51_27_fu_1378_p1;
wire   [9:0] zext_ln51_26_fu_1375_p1;
wire   [9:0] zext_ln51_25_fu_1372_p1;
wire   [9:0] zext_ln51_24_fu_1369_p1;
wire   [9:0] zext_ln51_23_fu_1366_p1;
wire   [9:0] zext_ln51_22_fu_1363_p1;
wire   [9:0] zext_ln51_21_fu_1360_p1;
wire   [9:0] zext_ln51_20_fu_1357_p1;
wire   [9:0] zext_ln51_19_fu_1354_p1;
wire   [9:0] zext_ln51_18_fu_1351_p1;
wire   [9:0] zext_ln51_17_fu_1348_p1;
wire   [9:0] zext_ln51_16_fu_1345_p1;
wire   [9:0] zext_ln51_15_fu_1342_p1;
wire   [9:0] zext_ln51_14_fu_1339_p1;
wire   [9:0] zext_ln51_13_fu_1336_p1;
wire   [9:0] zext_ln51_12_fu_1333_p1;
wire   [9:0] zext_ln51_11_fu_1330_p1;
wire   [9:0] zext_ln51_10_fu_1327_p1;
wire   [9:0] zext_ln51_9_fu_1324_p1;
wire   [9:0] zext_ln51_8_fu_1321_p1;
wire   [9:0] zext_ln51_7_fu_1318_p1;
wire   [9:0] zext_ln51_6_fu_1315_p1;
wire   [9:0] zext_ln51_5_fu_1312_p1;
wire   [9:0] zext_ln51_4_fu_1309_p1;
wire   [9:0] zext_ln51_3_fu_1306_p1;
wire   [9:0] zext_ln51_fu_1303_p1;
wire   [318:0] or_ln57_s_fu_1396_p33;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_10_reg_1503 <= select_ln51_10_fu_959_p3;
        select_ln51_11_reg_1508 <= select_ln51_11_fu_973_p3;
        select_ln51_12_reg_1513 <= select_ln51_12_fu_987_p3;
        select_ln51_13_reg_1518 <= select_ln51_13_fu_1001_p3;
        select_ln51_14_reg_1523 <= select_ln51_14_fu_1015_p3;
        select_ln51_15_reg_1528 <= select_ln51_15_fu_1029_p3;
        select_ln51_16_reg_1533 <= select_ln51_16_fu_1043_p3;
        select_ln51_17_reg_1538 <= select_ln51_17_fu_1057_p3;
        select_ln51_18_reg_1543 <= select_ln51_18_fu_1071_p3;
        select_ln51_19_reg_1548 <= select_ln51_19_fu_1085_p3;
        select_ln51_20_reg_1553 <= select_ln51_20_fu_1099_p3;
        select_ln51_21_reg_1558 <= select_ln51_21_fu_1113_p3;
        select_ln51_22_reg_1563 <= select_ln51_22_fu_1127_p3;
        select_ln51_23_reg_1568 <= select_ln51_23_fu_1141_p3;
        select_ln51_24_reg_1573 <= select_ln51_24_fu_1155_p3;
        select_ln51_25_reg_1578 <= select_ln51_25_fu_1169_p3;
        select_ln51_26_reg_1583 <= select_ln51_26_fu_1183_p3;
        select_ln51_27_reg_1588 <= select_ln51_27_fu_1197_p3;
        select_ln51_28_reg_1593 <= select_ln51_28_fu_1211_p3;
        select_ln51_29_reg_1598 <= select_ln51_29_fu_1225_p3;
        select_ln51_30_reg_1603 <= select_ln51_30_fu_1239_p3;
        select_ln51_31_reg_1608 <= select_ln51_31_fu_1253_p3;
        select_ln51_32_reg_1613 <= select_ln51_32_fu_1267_p3;
        select_ln51_33_reg_1618 <= select_ln51_33_fu_1281_p3;
        select_ln51_34_reg_1623 <= select_ln51_34_fu_1295_p3;
        select_ln51_4_reg_1473 <= select_ln51_4_fu_875_p3;
        select_ln51_5_reg_1478 <= select_ln51_5_fu_889_p3;
        select_ln51_6_reg_1483 <= select_ln51_6_fu_903_p3;
        select_ln51_7_reg_1488 <= select_ln51_7_fu_917_p3;
        select_ln51_8_reg_1493 <= select_ln51_8_fu_931_p3;
        select_ln51_9_reg_1498 <= select_ln51_9_fu_945_p3;
        select_ln51_reg_1468 <= select_ln51_fu_861_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer17_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_blk_n = layer15_out_empty_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_read_local = 1'b1;
    end else begin
        layer15_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer17_out_blk_n = layer17_out_full_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer17_out_write_local = 1'b1;
    end else begin
        layer17_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer17_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer15_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_897_p2 = (($signed(trunc_ln44_2_fu_275_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_911_p2 = (($signed(trunc_ln44_4_fu_295_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_925_p2 = (($signed(trunc_ln44_6_fu_315_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_939_p2 = (($signed(trunc_ln44_10_fu_335_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_953_p2 = (($signed(trunc_ln44_12_fu_355_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_967_p2 = (($signed(trunc_ln44_14_fu_375_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_981_p2 = (($signed(trunc_ln44_16_fu_395_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_995_p2 = (($signed(trunc_ln44_17_fu_415_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_1009_p2 = (($signed(trunc_ln44_18_fu_435_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_1023_p2 = (($signed(trunc_ln44_19_fu_455_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_1037_p2 = (($signed(trunc_ln44_20_fu_475_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_1051_p2 = (($signed(trunc_ln44_21_fu_495_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_1065_p2 = (($signed(trunc_ln44_22_fu_515_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_1079_p2 = (($signed(trunc_ln44_23_fu_535_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1093_p2 = (($signed(trunc_ln44_24_fu_555_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1107_p2 = (($signed(trunc_ln44_25_fu_575_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1121_p2 = (($signed(trunc_ln44_26_fu_595_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_1135_p2 = (($signed(trunc_ln44_27_fu_615_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_1149_p2 = (($signed(trunc_ln44_28_fu_635_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_1163_p2 = (($signed(trunc_ln44_29_fu_655_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_1177_p2 = (($signed(trunc_ln44_30_fu_675_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_1191_p2 = (($signed(trunc_ln44_31_fu_695_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_1205_p2 = (($signed(trunc_ln44_32_fu_715_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_1219_p2 = (($signed(trunc_ln44_33_fu_735_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1233_p2 = (($signed(trunc_ln44_34_fu_755_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_1247_p2 = (($signed(trunc_ln44_35_fu_775_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_1261_p2 = (($signed(trunc_ln44_36_fu_795_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_1275_p2 = (($signed(trunc_ln44_37_fu_815_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_1289_p2 = (($signed(trunc_ln44_38_fu_835_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_869_p2 = (($signed(trunc_ln44_8_fu_235_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_883_p2 = (($signed(trunc_ln44_9_fu_255_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_855_p2 = (($signed(trunc_ln44_fu_227_p1) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign layer15_out_read = layer15_out_read_local;

assign layer17_out_din = zext_ln57_fu_1463_p1;

assign layer17_out_write = layer17_out_write_local;

assign or_ln57_s_fu_1396_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_34_reg_1623}, {zext_ln51_32_fu_1393_p1}}, {zext_ln51_31_fu_1390_p1}}, {zext_ln51_30_fu_1387_p1}}, {zext_ln51_29_fu_1384_p1}}, {zext_ln51_28_fu_1381_p1}}, {zext_ln51_27_fu_1378_p1}}, {zext_ln51_26_fu_1375_p1}}, {zext_ln51_25_fu_1372_p1}}, {zext_ln51_24_fu_1369_p1}}, {zext_ln51_23_fu_1366_p1}}, {zext_ln51_22_fu_1363_p1}}, {zext_ln51_21_fu_1360_p1}}, {zext_ln51_20_fu_1357_p1}}, {zext_ln51_19_fu_1354_p1}}, {zext_ln51_18_fu_1351_p1}}, {zext_ln51_17_fu_1348_p1}}, {zext_ln51_16_fu_1345_p1}}, {zext_ln51_15_fu_1342_p1}}, {zext_ln51_14_fu_1339_p1}}, {zext_ln51_13_fu_1336_p1}}, {zext_ln51_12_fu_1333_p1}}, {zext_ln51_11_fu_1330_p1}}, {zext_ln51_10_fu_1327_p1}}, {zext_ln51_9_fu_1324_p1}}, {zext_ln51_8_fu_1321_p1}}, {zext_ln51_7_fu_1318_p1}}, {zext_ln51_6_fu_1315_p1}}, {zext_ln51_5_fu_1312_p1}}, {zext_ln51_4_fu_1309_p1}}, {zext_ln51_3_fu_1306_p1}}, {zext_ln51_fu_1303_p1}};

assign select_ln51_10_fu_959_p3 = ((icmp_ln51_14_fu_953_p2[0:0] == 1'b1) ? trunc_ln44_13_fu_365_p4 : 9'd0);

assign select_ln51_11_fu_973_p3 = ((icmp_ln51_15_fu_967_p2[0:0] == 1'b1) ? trunc_ln44_15_fu_385_p4 : 9'd0);

assign select_ln51_12_fu_987_p3 = ((icmp_ln51_16_fu_981_p2[0:0] == 1'b1) ? trunc_ln44_39_fu_405_p4 : 9'd0);

assign select_ln51_13_fu_1001_p3 = ((icmp_ln51_17_fu_995_p2[0:0] == 1'b1) ? trunc_ln44_40_fu_425_p4 : 9'd0);

assign select_ln51_14_fu_1015_p3 = ((icmp_ln51_18_fu_1009_p2[0:0] == 1'b1) ? trunc_ln44_41_fu_445_p4 : 9'd0);

assign select_ln51_15_fu_1029_p3 = ((icmp_ln51_19_fu_1023_p2[0:0] == 1'b1) ? trunc_ln44_42_fu_465_p4 : 9'd0);

assign select_ln51_16_fu_1043_p3 = ((icmp_ln51_20_fu_1037_p2[0:0] == 1'b1) ? trunc_ln44_43_fu_485_p4 : 9'd0);

assign select_ln51_17_fu_1057_p3 = ((icmp_ln51_21_fu_1051_p2[0:0] == 1'b1) ? trunc_ln44_44_fu_505_p4 : 9'd0);

assign select_ln51_18_fu_1071_p3 = ((icmp_ln51_22_fu_1065_p2[0:0] == 1'b1) ? trunc_ln44_45_fu_525_p4 : 9'd0);

assign select_ln51_19_fu_1085_p3 = ((icmp_ln51_23_fu_1079_p2[0:0] == 1'b1) ? trunc_ln44_46_fu_545_p4 : 9'd0);

assign select_ln51_20_fu_1099_p3 = ((icmp_ln51_24_fu_1093_p2[0:0] == 1'b1) ? trunc_ln44_47_fu_565_p4 : 9'd0);

assign select_ln51_21_fu_1113_p3 = ((icmp_ln51_25_fu_1107_p2[0:0] == 1'b1) ? trunc_ln44_48_fu_585_p4 : 9'd0);

assign select_ln51_22_fu_1127_p3 = ((icmp_ln51_26_fu_1121_p2[0:0] == 1'b1) ? trunc_ln44_49_fu_605_p4 : 9'd0);

assign select_ln51_23_fu_1141_p3 = ((icmp_ln51_27_fu_1135_p2[0:0] == 1'b1) ? trunc_ln44_50_fu_625_p4 : 9'd0);

assign select_ln51_24_fu_1155_p3 = ((icmp_ln51_28_fu_1149_p2[0:0] == 1'b1) ? trunc_ln44_51_fu_645_p4 : 9'd0);

assign select_ln51_25_fu_1169_p3 = ((icmp_ln51_29_fu_1163_p2[0:0] == 1'b1) ? trunc_ln44_52_fu_665_p4 : 9'd0);

assign select_ln51_26_fu_1183_p3 = ((icmp_ln51_30_fu_1177_p2[0:0] == 1'b1) ? trunc_ln44_53_fu_685_p4 : 9'd0);

assign select_ln51_27_fu_1197_p3 = ((icmp_ln51_31_fu_1191_p2[0:0] == 1'b1) ? trunc_ln44_54_fu_705_p4 : 9'd0);

assign select_ln51_28_fu_1211_p3 = ((icmp_ln51_32_fu_1205_p2[0:0] == 1'b1) ? trunc_ln44_55_fu_725_p4 : 9'd0);

assign select_ln51_29_fu_1225_p3 = ((icmp_ln51_33_fu_1219_p2[0:0] == 1'b1) ? trunc_ln44_56_fu_745_p4 : 9'd0);

assign select_ln51_30_fu_1239_p3 = ((icmp_ln51_34_fu_1233_p2[0:0] == 1'b1) ? trunc_ln44_57_fu_765_p4 : 9'd0);

assign select_ln51_31_fu_1253_p3 = ((icmp_ln51_35_fu_1247_p2[0:0] == 1'b1) ? trunc_ln44_58_fu_785_p4 : 9'd0);

assign select_ln51_32_fu_1267_p3 = ((icmp_ln51_36_fu_1261_p2[0:0] == 1'b1) ? trunc_ln44_59_fu_805_p4 : 9'd0);

assign select_ln51_33_fu_1281_p3 = ((icmp_ln51_37_fu_1275_p2[0:0] == 1'b1) ? trunc_ln44_60_fu_825_p4 : 9'd0);

assign select_ln51_34_fu_1295_p3 = ((icmp_ln51_38_fu_1289_p2[0:0] == 1'b1) ? trunc_ln1_fu_845_p4 : 9'd0);

assign select_ln51_4_fu_875_p3 = ((icmp_ln51_8_fu_869_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_245_p4 : 9'd0);

assign select_ln51_5_fu_889_p3 = ((icmp_ln51_9_fu_883_p2[0:0] == 1'b1) ? trunc_ln44_1_fu_265_p4 : 9'd0);

assign select_ln51_6_fu_903_p3 = ((icmp_ln51_10_fu_897_p2[0:0] == 1'b1) ? trunc_ln44_3_fu_285_p4 : 9'd0);

assign select_ln51_7_fu_917_p3 = ((icmp_ln51_11_fu_911_p2[0:0] == 1'b1) ? trunc_ln44_5_fu_305_p4 : 9'd0);

assign select_ln51_8_fu_931_p3 = ((icmp_ln51_12_fu_925_p2[0:0] == 1'b1) ? trunc_ln44_7_fu_325_p4 : 9'd0);

assign select_ln51_9_fu_945_p3 = ((icmp_ln51_13_fu_939_p2[0:0] == 1'b1) ? trunc_ln44_11_fu_345_p4 : 9'd0);

assign select_ln51_fu_861_p3 = ((icmp_ln51_fu_855_p2[0:0] == 1'b1) ? trunc_ln44_69_fu_231_p1 : 9'd0);

assign start_out = real_start;

assign trunc_ln1_fu_845_p4 = {{layer15_out_dout[318:310]}};

assign trunc_ln44_10_fu_335_p4 = {{layer15_out_dout[69:60]}};

assign trunc_ln44_11_fu_345_p4 = {{layer15_out_dout[68:60]}};

assign trunc_ln44_12_fu_355_p4 = {{layer15_out_dout[79:70]}};

assign trunc_ln44_13_fu_365_p4 = {{layer15_out_dout[78:70]}};

assign trunc_ln44_14_fu_375_p4 = {{layer15_out_dout[89:80]}};

assign trunc_ln44_15_fu_385_p4 = {{layer15_out_dout[88:80]}};

assign trunc_ln44_16_fu_395_p4 = {{layer15_out_dout[99:90]}};

assign trunc_ln44_17_fu_415_p4 = {{layer15_out_dout[109:100]}};

assign trunc_ln44_18_fu_435_p4 = {{layer15_out_dout[119:110]}};

assign trunc_ln44_19_fu_455_p4 = {{layer15_out_dout[129:120]}};

assign trunc_ln44_1_fu_265_p4 = {{layer15_out_dout[28:20]}};

assign trunc_ln44_20_fu_475_p4 = {{layer15_out_dout[139:130]}};

assign trunc_ln44_21_fu_495_p4 = {{layer15_out_dout[149:140]}};

assign trunc_ln44_22_fu_515_p4 = {{layer15_out_dout[159:150]}};

assign trunc_ln44_23_fu_535_p4 = {{layer15_out_dout[169:160]}};

assign trunc_ln44_24_fu_555_p4 = {{layer15_out_dout[179:170]}};

assign trunc_ln44_25_fu_575_p4 = {{layer15_out_dout[189:180]}};

assign trunc_ln44_26_fu_595_p4 = {{layer15_out_dout[199:190]}};

assign trunc_ln44_27_fu_615_p4 = {{layer15_out_dout[209:200]}};

assign trunc_ln44_28_fu_635_p4 = {{layer15_out_dout[219:210]}};

assign trunc_ln44_29_fu_655_p4 = {{layer15_out_dout[229:220]}};

assign trunc_ln44_2_fu_275_p4 = {{layer15_out_dout[39:30]}};

assign trunc_ln44_30_fu_675_p4 = {{layer15_out_dout[239:230]}};

assign trunc_ln44_31_fu_695_p4 = {{layer15_out_dout[249:240]}};

assign trunc_ln44_32_fu_715_p4 = {{layer15_out_dout[259:250]}};

assign trunc_ln44_33_fu_735_p4 = {{layer15_out_dout[269:260]}};

assign trunc_ln44_34_fu_755_p4 = {{layer15_out_dout[279:270]}};

assign trunc_ln44_35_fu_775_p4 = {{layer15_out_dout[289:280]}};

assign trunc_ln44_36_fu_795_p4 = {{layer15_out_dout[299:290]}};

assign trunc_ln44_37_fu_815_p4 = {{layer15_out_dout[309:300]}};

assign trunc_ln44_38_fu_835_p4 = {{layer15_out_dout[319:310]}};

assign trunc_ln44_39_fu_405_p4 = {{layer15_out_dout[98:90]}};

assign trunc_ln44_3_fu_285_p4 = {{layer15_out_dout[38:30]}};

assign trunc_ln44_40_fu_425_p4 = {{layer15_out_dout[108:100]}};

assign trunc_ln44_41_fu_445_p4 = {{layer15_out_dout[118:110]}};

assign trunc_ln44_42_fu_465_p4 = {{layer15_out_dout[128:120]}};

assign trunc_ln44_43_fu_485_p4 = {{layer15_out_dout[138:130]}};

assign trunc_ln44_44_fu_505_p4 = {{layer15_out_dout[148:140]}};

assign trunc_ln44_45_fu_525_p4 = {{layer15_out_dout[158:150]}};

assign trunc_ln44_46_fu_545_p4 = {{layer15_out_dout[168:160]}};

assign trunc_ln44_47_fu_565_p4 = {{layer15_out_dout[178:170]}};

assign trunc_ln44_48_fu_585_p4 = {{layer15_out_dout[188:180]}};

assign trunc_ln44_49_fu_605_p4 = {{layer15_out_dout[198:190]}};

assign trunc_ln44_4_fu_295_p4 = {{layer15_out_dout[49:40]}};

assign trunc_ln44_50_fu_625_p4 = {{layer15_out_dout[208:200]}};

assign trunc_ln44_51_fu_645_p4 = {{layer15_out_dout[218:210]}};

assign trunc_ln44_52_fu_665_p4 = {{layer15_out_dout[228:220]}};

assign trunc_ln44_53_fu_685_p4 = {{layer15_out_dout[238:230]}};

assign trunc_ln44_54_fu_705_p4 = {{layer15_out_dout[248:240]}};

assign trunc_ln44_55_fu_725_p4 = {{layer15_out_dout[258:250]}};

assign trunc_ln44_56_fu_745_p4 = {{layer15_out_dout[268:260]}};

assign trunc_ln44_57_fu_765_p4 = {{layer15_out_dout[278:270]}};

assign trunc_ln44_58_fu_785_p4 = {{layer15_out_dout[288:280]}};

assign trunc_ln44_59_fu_805_p4 = {{layer15_out_dout[298:290]}};

assign trunc_ln44_5_fu_305_p4 = {{layer15_out_dout[48:40]}};

assign trunc_ln44_60_fu_825_p4 = {{layer15_out_dout[308:300]}};

assign trunc_ln44_69_fu_231_p1 = layer15_out_dout[8:0];

assign trunc_ln44_6_fu_315_p4 = {{layer15_out_dout[59:50]}};

assign trunc_ln44_7_fu_325_p4 = {{layer15_out_dout[58:50]}};

assign trunc_ln44_8_fu_235_p4 = {{layer15_out_dout[19:10]}};

assign trunc_ln44_9_fu_255_p4 = {{layer15_out_dout[29:20]}};

assign trunc_ln44_fu_227_p1 = layer15_out_dout[9:0];

assign trunc_ln44_s_fu_245_p4 = {{layer15_out_dout[18:10]}};

assign zext_ln51_10_fu_1327_p1 = select_ln51_11_reg_1508;

assign zext_ln51_11_fu_1330_p1 = select_ln51_12_reg_1513;

assign zext_ln51_12_fu_1333_p1 = select_ln51_13_reg_1518;

assign zext_ln51_13_fu_1336_p1 = select_ln51_14_reg_1523;

assign zext_ln51_14_fu_1339_p1 = select_ln51_15_reg_1528;

assign zext_ln51_15_fu_1342_p1 = select_ln51_16_reg_1533;

assign zext_ln51_16_fu_1345_p1 = select_ln51_17_reg_1538;

assign zext_ln51_17_fu_1348_p1 = select_ln51_18_reg_1543;

assign zext_ln51_18_fu_1351_p1 = select_ln51_19_reg_1548;

assign zext_ln51_19_fu_1354_p1 = select_ln51_20_reg_1553;

assign zext_ln51_20_fu_1357_p1 = select_ln51_21_reg_1558;

assign zext_ln51_21_fu_1360_p1 = select_ln51_22_reg_1563;

assign zext_ln51_22_fu_1363_p1 = select_ln51_23_reg_1568;

assign zext_ln51_23_fu_1366_p1 = select_ln51_24_reg_1573;

assign zext_ln51_24_fu_1369_p1 = select_ln51_25_reg_1578;

assign zext_ln51_25_fu_1372_p1 = select_ln51_26_reg_1583;

assign zext_ln51_26_fu_1375_p1 = select_ln51_27_reg_1588;

assign zext_ln51_27_fu_1378_p1 = select_ln51_28_reg_1593;

assign zext_ln51_28_fu_1381_p1 = select_ln51_29_reg_1598;

assign zext_ln51_29_fu_1384_p1 = select_ln51_30_reg_1603;

assign zext_ln51_30_fu_1387_p1 = select_ln51_31_reg_1608;

assign zext_ln51_31_fu_1390_p1 = select_ln51_32_reg_1613;

assign zext_ln51_32_fu_1393_p1 = select_ln51_33_reg_1618;

assign zext_ln51_3_fu_1306_p1 = select_ln51_4_reg_1473;

assign zext_ln51_4_fu_1309_p1 = select_ln51_5_reg_1478;

assign zext_ln51_5_fu_1312_p1 = select_ln51_6_reg_1483;

assign zext_ln51_6_fu_1315_p1 = select_ln51_7_reg_1488;

assign zext_ln51_7_fu_1318_p1 = select_ln51_8_reg_1493;

assign zext_ln51_8_fu_1321_p1 = select_ln51_9_reg_1498;

assign zext_ln51_9_fu_1324_p1 = select_ln51_10_reg_1503;

assign zext_ln51_fu_1303_p1 = select_ln51_reg_1468;

assign zext_ln57_fu_1463_p1 = or_ln57_s_fu_1396_p33;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_s
