// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_elem_0_0_0_0_0_val,
        in_elem_0_1_0_0_0_val,
        in_elem_0_2_0_0_0_val,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_i,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] in_elem_0_0_0_0_0_val;
input  [9:0] in_elem_0_1_0_0_0_val;
input  [9:0] in_elem_0_2_0_0_0_val;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o_ap_vld;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o_ap_vld;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o_ap_vld;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o_ap_vld;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o_ap_vld;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o_ap_vld;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68_ap_vld;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld;
input  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
output  [9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
output   void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o_ap_vld;
input  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_i;
output  [9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o;
output   p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o_ap_vld;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o_ap_vld;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o_ap_vld;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o_ap_vld;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o_ap_vld;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o_ap_vld;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68_ap_vld;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld;
reg[9:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
reg void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o_ap_vld;
reg[9:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o;
reg p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_q0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_q0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_q0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_q0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_q0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_ce0;
reg    p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_we0;
wire   [9:0] p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_q0;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
end

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_we0),
    .d0(in_elem_0_0_0_0_0_val),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_q0)
);

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_we0),
    .d0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_q0),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_q0)
);

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_we0),
    .d0(in_elem_0_1_0_0_0_val),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_q0)
);

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_we0),
    .d0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_q0),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_q0)
);

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_we0),
    .d0(in_elem_0_2_0_0_0_val),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_q0)
);

myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s_p_ZZN4nnet17conv_2d_bkb #(
    .DataWidth( 10 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd33),
    .ce0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_ce0),
    .we0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_we0),
    .d0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_q0),
    .q0(p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_ce0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_we0 = 1'd1;
    end else begin
        p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o = in_elem_0_2_0_0_0_val;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o = in_elem_0_1_0_0_0_val;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o = in_elem_0_0_0_0_0_val;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_62_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_63_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_64_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_19_q0;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_20_q0;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_21_q0;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_71_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_72_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_73_i;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_16_q0;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_17_q0;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o = p_ZZN4nnet17conv_2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9ap_o_mo_18_q0;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_i;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_68 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_65_i;

assign p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_69 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_66_i;

assign p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_70 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_67_i;

assign p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_77 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_74_i;

assign p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_78 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_75_i;

assign void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 = p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode5EL9_76_i;

assign void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;

assign void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_i;

assign void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_19 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i;

endmodule //myproject_shift_line_buffer_array_ap_fixed_10_4_5_3_0_3u_config2_s
