// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer17_out_dout,
        layer17_out_num_data_valid,
        layer17_out_fifo_cap,
        layer17_out_empty_n,
        layer17_out_read,
        layer18_out_TDATA,
        layer18_out_TVALID,
        layer18_out_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [319:0] layer17_out_dout;
input  [1:0] layer17_out_num_data_valid;
input  [1:0] layer17_out_fifo_cap;
input   layer17_out_empty_n;
output   layer17_out_read;
output  [79:0] layer18_out_TDATA;
output   layer18_out_TVALID;
input   layer18_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer17_out_blk_n;
reg    layer18_out_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [9:0] data_fu_209_p1;
reg   [9:0] data_reg_602;
reg    ap_block_state1;
reg   [9:0] data_1_reg_607;
reg   [9:0] data_2_reg_612;
reg   [9:0] data_3_reg_617;
reg   [9:0] data_4_reg_622;
reg   [9:0] data_5_reg_627;
reg   [9:0] data_6_reg_632;
reg   [9:0] data_7_reg_637;
reg   [9:0] data_8_reg_642;
reg   [9:0] data_9_reg_647;
reg   [9:0] data_31_reg_652;
reg   [9:0] data_10_reg_657;
reg   [9:0] data_11_reg_662;
reg   [9:0] data_12_reg_667;
reg   [9:0] data_13_reg_672;
reg   [9:0] data_14_reg_677;
reg   [9:0] data_15_reg_682;
reg   [9:0] data_16_reg_687;
reg   [9:0] data_17_reg_692;
reg   [9:0] data_18_reg_697;
reg   [9:0] data_19_reg_702;
reg   [9:0] data_20_reg_707;
reg   [9:0] data_21_reg_712;
reg   [9:0] data_22_reg_717;
reg   [9:0] data_23_reg_722;
reg   [9:0] data_24_reg_727;
reg   [9:0] data_25_reg_732;
reg   [9:0] data_26_reg_737;
reg   [9:0] data_27_reg_742;
reg   [9:0] data_28_reg_747;
reg   [9:0] data_29_reg_752;
reg   [9:0] data_30_reg_757;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready;
wire   [9:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0;
wire   [9:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1;
wire   [9:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2;
wire   [9:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3;
wire   [9:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg;
reg    ap_block_state1_ignore_call35;
reg    layer17_out_read_local;
wire   [73:0] tmp_fu_575_p10;
wire    regslice_both_layer18_out_U_apdone_blk;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [79:0] layer18_out_TDATA_int_regslice;
reg    layer18_out_TVALID_int_regslice;
wire    layer18_out_TREADY_int_regslice;
wire    regslice_both_layer18_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg = 1'b0;
end

myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready),
    .data_0_val(data_reg_602),
    .data_1_val(data_1_reg_607),
    .data_2_val(data_2_reg_612),
    .data_3_val(data_3_reg_617),
    .data_4_val(data_4_reg_622),
    .data_5_val(data_5_reg_627),
    .data_6_val(data_6_reg_632),
    .data_7_val(data_7_reg_637),
    .data_8_val(data_8_reg_642),
    .data_9_val(data_9_reg_647),
    .data_10_val(data_31_reg_652),
    .data_11_val(data_10_reg_657),
    .data_12_val(data_11_reg_662),
    .data_13_val(data_12_reg_667),
    .data_14_val(data_13_reg_672),
    .data_15_val(data_14_reg_677),
    .data_16_val(data_15_reg_682),
    .data_17_val(data_16_reg_687),
    .data_18_val(data_17_reg_692),
    .data_19_val(data_18_reg_697),
    .data_20_val(data_19_reg_702),
    .data_21_val(data_20_reg_707),
    .data_22_val(data_21_reg_712),
    .data_23_val(data_22_reg_717),
    .data_24_val(data_23_reg_722),
    .data_25_val(data_24_reg_727),
    .data_26_val(data_25_reg_732),
    .data_27_val(data_26_reg_737),
    .data_28_val(data_27_reg_742),
    .data_29_val(data_28_reg_747),
    .data_30_val(data_29_reg_752),
    .data_31_val(data_30_reg_757),
    .ap_return_0(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4)
);

myproject_regslice_both #(
    .DataWidth( 80 ))
regslice_both_layer18_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer18_out_TDATA_int_regslice),
    .vld_in(layer18_out_TVALID_int_regslice),
    .ack_in(layer18_out_TREADY_int_regslice),
    .data_out(layer18_out_TDATA),
    .vld_out(regslice_both_layer18_out_U_vld_out),
    .ack_out(layer18_out_TREADY),
    .apdone_blk(regslice_both_layer18_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call35) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_10_reg_657 <= {{layer17_out_dout[119:110]}};
        data_11_reg_662 <= {{layer17_out_dout[129:120]}};
        data_12_reg_667 <= {{layer17_out_dout[139:130]}};
        data_13_reg_672 <= {{layer17_out_dout[149:140]}};
        data_14_reg_677 <= {{layer17_out_dout[159:150]}};
        data_15_reg_682 <= {{layer17_out_dout[169:160]}};
        data_16_reg_687 <= {{layer17_out_dout[179:170]}};
        data_17_reg_692 <= {{layer17_out_dout[189:180]}};
        data_18_reg_697 <= {{layer17_out_dout[199:190]}};
        data_19_reg_702 <= {{layer17_out_dout[209:200]}};
        data_1_reg_607 <= {{layer17_out_dout[19:10]}};
        data_20_reg_707 <= {{layer17_out_dout[219:210]}};
        data_21_reg_712 <= {{layer17_out_dout[229:220]}};
        data_22_reg_717 <= {{layer17_out_dout[239:230]}};
        data_23_reg_722 <= {{layer17_out_dout[249:240]}};
        data_24_reg_727 <= {{layer17_out_dout[259:250]}};
        data_25_reg_732 <= {{layer17_out_dout[269:260]}};
        data_26_reg_737 <= {{layer17_out_dout[279:270]}};
        data_27_reg_742 <= {{layer17_out_dout[289:280]}};
        data_28_reg_747 <= {{layer17_out_dout[299:290]}};
        data_29_reg_752 <= {{layer17_out_dout[309:300]}};
        data_2_reg_612 <= {{layer17_out_dout[29:20]}};
        data_30_reg_757 <= {{layer17_out_dout[319:310]}};
        data_31_reg_652 <= {{layer17_out_dout[109:100]}};
        data_3_reg_617 <= {{layer17_out_dout[39:30]}};
        data_4_reg_622 <= {{layer17_out_dout[49:40]}};
        data_5_reg_627 <= {{layer17_out_dout[59:50]}};
        data_6_reg_632 <= {{layer17_out_dout[69:60]}};
        data_7_reg_637 <= {{layer17_out_dout[79:70]}};
        data_8_reg_642 <= {{layer17_out_dout[89:80]}};
        data_9_reg_647 <= {{layer17_out_dout[99:90]}};
        data_reg_602 <= data_fu_209_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer18_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer18_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer17_out_blk_n = layer17_out_empty_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer17_out_read_local = 1'b1;
    end else begin
        layer17_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        layer18_out_TDATA_blk_n = layer18_out_TREADY_int_regslice;
    end else begin
        layer18_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer18_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer18_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((layer18_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call35 = ((ap_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((layer18_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer18_out_U_apdone_blk == 1'b1));
end

assign data_fu_209_p1 = layer17_out_dout[9:0];

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_start_reg;

assign layer17_out_read = layer17_out_read_local;

assign layer18_out_TDATA_int_regslice = tmp_fu_575_p10;

assign layer18_out_TVALID = regslice_both_layer18_out_U_vld_out;

assign tmp_fu_575_p10 = {{{{{{{{{grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_4}, {6'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_3}}, {6'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_2}}, {6'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_1}}, {6'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_10_4_5_3_0_config18_s_fu_171_ap_return_0}};

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_s
