// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer10_out_dout,
        layer10_out_num_data_valid,
        layer10_out_fifo_cap,
        layer10_out_empty_n,
        layer10_out_read,
        layer12_out_din,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer12_out_full_n,
        layer12_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [319:0] layer10_out_dout;
input  [6:0] layer10_out_num_data_valid;
input  [6:0] layer10_out_fifo_cap;
input   layer10_out_empty_n;
output   layer10_out_read;
output  [319:0] layer12_out_din;
input  [6:0] layer12_out_num_data_valid;
input  [6:0] layer12_out_fifo_cap;
input   layer12_out_full_n;
output   layer12_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_1339_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer10_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer12_out_blk_n;
wire   [8:0] out_data_8_fu_891_p3;
reg   [8:0] out_data_8_reg_1522;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] out_data_10_fu_905_p3;
reg   [8:0] out_data_10_reg_1527;
wire   [8:0] out_data_12_fu_919_p3;
reg   [8:0] out_data_12_reg_1532;
wire   [8:0] out_data_13_fu_933_p3;
reg   [8:0] out_data_13_reg_1537;
wire   [8:0] select_ln51_fu_947_p3;
reg   [8:0] select_ln51_reg_1542;
wire   [8:0] select_ln51_35_fu_961_p3;
reg   [8:0] select_ln51_35_reg_1547;
wire   [8:0] select_ln51_36_fu_975_p3;
reg   [8:0] select_ln51_36_reg_1552;
wire   [8:0] select_ln51_37_fu_989_p3;
reg   [8:0] select_ln51_37_reg_1557;
wire   [8:0] select_ln51_38_fu_1003_p3;
reg   [8:0] select_ln51_38_reg_1562;
wire   [8:0] select_ln51_39_fu_1017_p3;
reg   [8:0] select_ln51_39_reg_1567;
wire   [8:0] select_ln51_40_fu_1031_p3;
reg   [8:0] select_ln51_40_reg_1572;
wire   [8:0] select_ln51_41_fu_1045_p3;
reg   [8:0] select_ln51_41_reg_1577;
wire   [8:0] select_ln51_42_fu_1059_p3;
reg   [8:0] select_ln51_42_reg_1582;
wire   [8:0] select_ln51_43_fu_1073_p3;
reg   [8:0] select_ln51_43_reg_1587;
wire   [8:0] select_ln51_44_fu_1087_p3;
reg   [8:0] select_ln51_44_reg_1592;
wire   [8:0] select_ln51_45_fu_1101_p3;
reg   [8:0] select_ln51_45_reg_1597;
wire   [8:0] select_ln51_46_fu_1115_p3;
reg   [8:0] select_ln51_46_reg_1602;
wire   [8:0] select_ln51_47_fu_1129_p3;
reg   [8:0] select_ln51_47_reg_1607;
wire   [8:0] select_ln51_48_fu_1143_p3;
reg   [8:0] select_ln51_48_reg_1612;
wire   [8:0] select_ln51_49_fu_1157_p3;
reg   [8:0] select_ln51_49_reg_1617;
wire   [8:0] select_ln51_50_fu_1171_p3;
reg   [8:0] select_ln51_50_reg_1622;
wire   [8:0] select_ln51_51_fu_1185_p3;
reg   [8:0] select_ln51_51_reg_1627;
wire   [8:0] select_ln51_52_fu_1199_p3;
reg   [8:0] select_ln51_52_reg_1632;
wire   [8:0] select_ln51_53_fu_1213_p3;
reg   [8:0] select_ln51_53_reg_1637;
wire   [8:0] select_ln51_54_fu_1227_p3;
reg   [8:0] select_ln51_54_reg_1642;
wire   [8:0] select_ln51_55_fu_1241_p3;
reg   [8:0] select_ln51_55_reg_1647;
wire   [8:0] select_ln51_56_fu_1255_p3;
reg   [8:0] select_ln51_56_reg_1652;
wire   [8:0] select_ln51_57_fu_1269_p3;
reg   [8:0] select_ln51_57_reg_1657;
wire   [8:0] select_ln51_58_fu_1283_p3;
reg   [8:0] select_ln51_58_reg_1662;
wire   [8:0] select_ln51_59_fu_1297_p3;
reg   [8:0] select_ln51_59_reg_1667;
wire   [8:0] select_ln51_60_fu_1311_p3;
reg   [8:0] select_ln51_60_reg_1672;
wire   [8:0] select_ln51_61_fu_1325_p3;
reg   [8:0] select_ln51_61_reg_1677;
reg   [5:0] i1_fu_232;
wire   [5:0] i_fu_1333_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i1_load;
reg    layer10_out_read_local;
wire   [319:0] zext_ln57_fu_1510_p1;
reg    ap_block_pp0_stage0_01001;
reg    layer12_out_write_local;
wire   [9:0] out_data_fu_257_p1;
wire   [0:0] icmp_ln51_fu_885_p2;
wire   [8:0] trunc_ln44_100_fu_261_p1;
wire   [9:0] out_data_9_fu_265_p4;
wire   [0:0] icmp_ln51_39_fu_899_p2;
wire   [8:0] trunc_ln44_s_fu_275_p4;
wire   [9:0] out_data_11_fu_285_p4;
wire   [0:0] icmp_ln51_40_fu_913_p2;
wire   [8:0] trunc_ln44_70_fu_295_p4;
wire   [9:0] out_data_1_fu_305_p4;
wire   [0:0] icmp_ln51_41_fu_927_p2;
wire   [8:0] trunc_ln44_71_fu_315_p4;
wire   [9:0] trunc_ln44_42_fu_325_p4;
wire   [0:0] icmp_ln51_42_fu_941_p2;
wire   [8:0] trunc_ln44_72_fu_335_p4;
wire   [9:0] trunc_ln44_43_fu_345_p4;
wire   [0:0] icmp_ln51_43_fu_955_p2;
wire   [8:0] trunc_ln44_73_fu_355_p4;
wire   [9:0] trunc_ln44_44_fu_365_p4;
wire   [0:0] icmp_ln51_44_fu_969_p2;
wire   [8:0] trunc_ln44_74_fu_375_p4;
wire   [9:0] trunc_ln44_45_fu_385_p4;
wire   [0:0] icmp_ln51_45_fu_983_p2;
wire   [8:0] trunc_ln44_75_fu_395_p4;
wire   [9:0] trunc_ln44_46_fu_405_p4;
wire   [0:0] icmp_ln51_46_fu_997_p2;
wire   [8:0] trunc_ln44_76_fu_415_p4;
wire   [9:0] trunc_ln44_47_fu_425_p4;
wire   [0:0] icmp_ln51_47_fu_1011_p2;
wire   [8:0] trunc_ln44_77_fu_435_p4;
wire   [9:0] trunc_ln44_48_fu_445_p4;
wire   [0:0] icmp_ln51_48_fu_1025_p2;
wire   [8:0] trunc_ln44_78_fu_455_p4;
wire   [9:0] trunc_ln44_49_fu_465_p4;
wire   [0:0] icmp_ln51_49_fu_1039_p2;
wire   [8:0] trunc_ln44_79_fu_475_p4;
wire   [9:0] trunc_ln44_50_fu_485_p4;
wire   [0:0] icmp_ln51_50_fu_1053_p2;
wire   [8:0] trunc_ln44_80_fu_495_p4;
wire   [9:0] trunc_ln44_51_fu_505_p4;
wire   [0:0] icmp_ln51_51_fu_1067_p2;
wire   [8:0] trunc_ln44_81_fu_515_p4;
wire   [9:0] trunc_ln44_52_fu_525_p4;
wire   [0:0] icmp_ln51_52_fu_1081_p2;
wire   [8:0] trunc_ln44_82_fu_535_p4;
wire   [9:0] trunc_ln44_53_fu_545_p4;
wire   [0:0] icmp_ln51_53_fu_1095_p2;
wire   [8:0] trunc_ln44_83_fu_555_p4;
wire   [9:0] trunc_ln44_54_fu_565_p4;
wire   [0:0] icmp_ln51_54_fu_1109_p2;
wire   [8:0] trunc_ln44_84_fu_575_p4;
wire   [9:0] trunc_ln44_55_fu_585_p4;
wire   [0:0] icmp_ln51_55_fu_1123_p2;
wire   [8:0] trunc_ln44_85_fu_595_p4;
wire   [9:0] trunc_ln44_56_fu_605_p4;
wire   [0:0] icmp_ln51_56_fu_1137_p2;
wire   [8:0] trunc_ln44_86_fu_615_p4;
wire   [9:0] trunc_ln44_57_fu_625_p4;
wire   [0:0] icmp_ln51_57_fu_1151_p2;
wire   [8:0] trunc_ln44_87_fu_635_p4;
wire   [9:0] trunc_ln44_58_fu_645_p4;
wire   [0:0] icmp_ln51_58_fu_1165_p2;
wire   [8:0] trunc_ln44_88_fu_655_p4;
wire   [9:0] trunc_ln44_59_fu_665_p4;
wire   [0:0] icmp_ln51_59_fu_1179_p2;
wire   [8:0] trunc_ln44_89_fu_675_p4;
wire   [9:0] trunc_ln44_60_fu_685_p4;
wire   [0:0] icmp_ln51_60_fu_1193_p2;
wire   [8:0] trunc_ln44_90_fu_695_p4;
wire   [9:0] trunc_ln44_61_fu_705_p4;
wire   [0:0] icmp_ln51_61_fu_1207_p2;
wire   [8:0] trunc_ln44_91_fu_715_p4;
wire   [9:0] trunc_ln44_62_fu_725_p4;
wire   [0:0] icmp_ln51_62_fu_1221_p2;
wire   [8:0] trunc_ln44_92_fu_735_p4;
wire   [9:0] trunc_ln44_63_fu_745_p4;
wire   [0:0] icmp_ln51_63_fu_1235_p2;
wire   [8:0] trunc_ln44_93_fu_755_p4;
wire   [9:0] trunc_ln44_64_fu_765_p4;
wire   [0:0] icmp_ln51_64_fu_1249_p2;
wire   [8:0] trunc_ln44_94_fu_775_p4;
wire   [9:0] trunc_ln44_65_fu_785_p4;
wire   [0:0] icmp_ln51_65_fu_1263_p2;
wire   [8:0] trunc_ln44_95_fu_795_p4;
wire   [9:0] trunc_ln44_66_fu_805_p4;
wire   [0:0] icmp_ln51_66_fu_1277_p2;
wire   [8:0] trunc_ln44_96_fu_815_p4;
wire   [9:0] trunc_ln44_67_fu_825_p4;
wire   [0:0] icmp_ln51_67_fu_1291_p2;
wire   [8:0] trunc_ln44_97_fu_835_p4;
wire   [9:0] trunc_ln44_68_fu_845_p4;
wire   [0:0] icmp_ln51_68_fu_1305_p2;
wire   [8:0] trunc_ln44_98_fu_855_p4;
wire   [9:0] trunc_ln44_69_fu_865_p4;
wire   [0:0] icmp_ln51_69_fu_1319_p2;
wire   [8:0] trunc_ln_fu_875_p4;
wire   [9:0] zext_ln51_58_fu_1440_p1;
wire   [9:0] zext_ln51_57_fu_1437_p1;
wire   [9:0] zext_ln51_56_fu_1434_p1;
wire   [9:0] zext_ln51_55_fu_1431_p1;
wire   [9:0] zext_ln51_54_fu_1428_p1;
wire   [9:0] zext_ln51_53_fu_1425_p1;
wire   [9:0] zext_ln51_52_fu_1422_p1;
wire   [9:0] zext_ln51_51_fu_1419_p1;
wire   [9:0] zext_ln51_50_fu_1416_p1;
wire   [9:0] zext_ln51_49_fu_1413_p1;
wire   [9:0] zext_ln51_48_fu_1410_p1;
wire   [9:0] zext_ln51_47_fu_1407_p1;
wire   [9:0] zext_ln51_46_fu_1404_p1;
wire   [9:0] zext_ln51_45_fu_1401_p1;
wire   [9:0] zext_ln51_44_fu_1398_p1;
wire   [9:0] zext_ln51_43_fu_1395_p1;
wire   [9:0] zext_ln51_42_fu_1392_p1;
wire   [9:0] zext_ln51_41_fu_1389_p1;
wire   [9:0] zext_ln51_40_fu_1386_p1;
wire   [9:0] zext_ln51_39_fu_1383_p1;
wire   [9:0] zext_ln51_38_fu_1380_p1;
wire   [9:0] zext_ln51_37_fu_1377_p1;
wire   [9:0] zext_ln51_36_fu_1374_p1;
wire   [9:0] zext_ln51_35_fu_1371_p1;
wire   [9:0] zext_ln51_34_fu_1368_p1;
wire   [9:0] zext_ln51_33_fu_1365_p1;
wire   [9:0] zext_ln51_fu_1362_p1;
wire   [9:0] zext_ln45_6_fu_1359_p1;
wire   [9:0] zext_ln45_5_fu_1356_p1;
wire   [9:0] zext_ln45_4_fu_1353_p1;
wire   [9:0] zext_ln45_fu_1350_p1;
wire   [318:0] or_ln57_s_fu_1443_p33;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_171;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i1_fu_232 = 6'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_171)) begin
        i1_fu_232 <= i_fu_1333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_10_reg_1527 <= out_data_10_fu_905_p3;
        out_data_12_reg_1532 <= out_data_12_fu_919_p3;
        out_data_13_reg_1537 <= out_data_13_fu_933_p3;
        out_data_8_reg_1522 <= out_data_8_fu_891_p3;
        select_ln51_35_reg_1547 <= select_ln51_35_fu_961_p3;
        select_ln51_36_reg_1552 <= select_ln51_36_fu_975_p3;
        select_ln51_37_reg_1557 <= select_ln51_37_fu_989_p3;
        select_ln51_38_reg_1562 <= select_ln51_38_fu_1003_p3;
        select_ln51_39_reg_1567 <= select_ln51_39_fu_1017_p3;
        select_ln51_40_reg_1572 <= select_ln51_40_fu_1031_p3;
        select_ln51_41_reg_1577 <= select_ln51_41_fu_1045_p3;
        select_ln51_42_reg_1582 <= select_ln51_42_fu_1059_p3;
        select_ln51_43_reg_1587 <= select_ln51_43_fu_1073_p3;
        select_ln51_44_reg_1592 <= select_ln51_44_fu_1087_p3;
        select_ln51_45_reg_1597 <= select_ln51_45_fu_1101_p3;
        select_ln51_46_reg_1602 <= select_ln51_46_fu_1115_p3;
        select_ln51_47_reg_1607 <= select_ln51_47_fu_1129_p3;
        select_ln51_48_reg_1612 <= select_ln51_48_fu_1143_p3;
        select_ln51_49_reg_1617 <= select_ln51_49_fu_1157_p3;
        select_ln51_50_reg_1622 <= select_ln51_50_fu_1171_p3;
        select_ln51_51_reg_1627 <= select_ln51_51_fu_1185_p3;
        select_ln51_52_reg_1632 <= select_ln51_52_fu_1199_p3;
        select_ln51_53_reg_1637 <= select_ln51_53_fu_1213_p3;
        select_ln51_54_reg_1642 <= select_ln51_54_fu_1227_p3;
        select_ln51_55_reg_1647 <= select_ln51_55_fu_1241_p3;
        select_ln51_56_reg_1652 <= select_ln51_56_fu_1255_p3;
        select_ln51_57_reg_1657 <= select_ln51_57_fu_1269_p3;
        select_ln51_58_reg_1662 <= select_ln51_58_fu_1283_p3;
        select_ln51_59_reg_1667 <= select_ln51_59_fu_1297_p3;
        select_ln51_60_reg_1672 <= select_ln51_60_fu_1311_p3;
        select_ln51_61_reg_1677 <= select_ln51_61_fu_1325_p3;
        select_ln51_reg_1542 <= select_ln51_fu_947_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_1339_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer10_out_blk_n = layer10_out_empty_n;
    end else begin
        layer10_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer10_out_read_local = 1'b1;
    end else begin
        layer10_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer12_out_write_local = 1'b1;
    end else begin
        layer12_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (layer10_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer12_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_171 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_fu_1333_p2 = (ap_sig_allocacmp_i1_load + 6'd1);

assign icmp_ln41_fu_1339_p2 = ((ap_sig_allocacmp_i1_load == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_899_p2 = (($signed(out_data_9_fu_265_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_913_p2 = (($signed(out_data_11_fu_285_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_927_p2 = (($signed(out_data_1_fu_305_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_941_p2 = (($signed(trunc_ln44_42_fu_325_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_955_p2 = (($signed(trunc_ln44_43_fu_345_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_969_p2 = (($signed(trunc_ln44_44_fu_365_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_983_p2 = (($signed(trunc_ln44_45_fu_385_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_997_p2 = (($signed(trunc_ln44_46_fu_405_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_1011_p2 = (($signed(trunc_ln44_47_fu_425_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_1025_p2 = (($signed(trunc_ln44_48_fu_445_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_1039_p2 = (($signed(trunc_ln44_49_fu_465_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_1053_p2 = (($signed(trunc_ln44_50_fu_485_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_1067_p2 = (($signed(trunc_ln44_51_fu_505_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_1081_p2 = (($signed(trunc_ln44_52_fu_525_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_1095_p2 = (($signed(trunc_ln44_53_fu_545_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_54_fu_1109_p2 = (($signed(trunc_ln44_54_fu_565_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_55_fu_1123_p2 = (($signed(trunc_ln44_55_fu_585_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_56_fu_1137_p2 = (($signed(trunc_ln44_56_fu_605_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_57_fu_1151_p2 = (($signed(trunc_ln44_57_fu_625_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_58_fu_1165_p2 = (($signed(trunc_ln44_58_fu_645_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_59_fu_1179_p2 = (($signed(trunc_ln44_59_fu_665_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_60_fu_1193_p2 = (($signed(trunc_ln44_60_fu_685_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_61_fu_1207_p2 = (($signed(trunc_ln44_61_fu_705_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_1221_p2 = (($signed(trunc_ln44_62_fu_725_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_63_fu_1235_p2 = (($signed(trunc_ln44_63_fu_745_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_64_fu_1249_p2 = (($signed(trunc_ln44_64_fu_765_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_65_fu_1263_p2 = (($signed(trunc_ln44_65_fu_785_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_66_fu_1277_p2 = (($signed(trunc_ln44_66_fu_805_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_67_fu_1291_p2 = (($signed(trunc_ln44_67_fu_825_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_68_fu_1305_p2 = (($signed(trunc_ln44_68_fu_845_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_69_fu_1319_p2 = (($signed(trunc_ln44_69_fu_865_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_885_p2 = (($signed(out_data_fu_257_p1) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign layer10_out_read = layer10_out_read_local;

assign layer12_out_din = zext_ln57_fu_1510_p1;

assign layer12_out_write = layer12_out_write_local;

assign or_ln57_s_fu_1443_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_61_reg_1677}, {zext_ln51_58_fu_1440_p1}}, {zext_ln51_57_fu_1437_p1}}, {zext_ln51_56_fu_1434_p1}}, {zext_ln51_55_fu_1431_p1}}, {zext_ln51_54_fu_1428_p1}}, {zext_ln51_53_fu_1425_p1}}, {zext_ln51_52_fu_1422_p1}}, {zext_ln51_51_fu_1419_p1}}, {zext_ln51_50_fu_1416_p1}}, {zext_ln51_49_fu_1413_p1}}, {zext_ln51_48_fu_1410_p1}}, {zext_ln51_47_fu_1407_p1}}, {zext_ln51_46_fu_1404_p1}}, {zext_ln51_45_fu_1401_p1}}, {zext_ln51_44_fu_1398_p1}}, {zext_ln51_43_fu_1395_p1}}, {zext_ln51_42_fu_1392_p1}}, {zext_ln51_41_fu_1389_p1}}, {zext_ln51_40_fu_1386_p1}}, {zext_ln51_39_fu_1383_p1}}, {zext_ln51_38_fu_1380_p1}}, {zext_ln51_37_fu_1377_p1}}, {zext_ln51_36_fu_1374_p1}}, {zext_ln51_35_fu_1371_p1}}, {zext_ln51_34_fu_1368_p1}}, {zext_ln51_33_fu_1365_p1}}, {zext_ln51_fu_1362_p1}}, {zext_ln45_6_fu_1359_p1}}, {zext_ln45_5_fu_1356_p1}}, {zext_ln45_4_fu_1353_p1}}, {zext_ln45_fu_1350_p1}};

assign out_data_10_fu_905_p3 = ((icmp_ln51_39_fu_899_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_275_p4 : 9'd0);

assign out_data_11_fu_285_p4 = {{layer10_out_dout[29:20]}};

assign out_data_12_fu_919_p3 = ((icmp_ln51_40_fu_913_p2[0:0] == 1'b1) ? trunc_ln44_70_fu_295_p4 : 9'd0);

assign out_data_13_fu_933_p3 = ((icmp_ln51_41_fu_927_p2[0:0] == 1'b1) ? trunc_ln44_71_fu_315_p4 : 9'd0);

assign out_data_1_fu_305_p4 = {{layer10_out_dout[39:30]}};

assign out_data_8_fu_891_p3 = ((icmp_ln51_fu_885_p2[0:0] == 1'b1) ? trunc_ln44_100_fu_261_p1 : 9'd0);

assign out_data_9_fu_265_p4 = {{layer10_out_dout[19:10]}};

assign out_data_fu_257_p1 = layer10_out_dout[9:0];

assign select_ln51_35_fu_961_p3 = ((icmp_ln51_43_fu_955_p2[0:0] == 1'b1) ? trunc_ln44_73_fu_355_p4 : 9'd0);

assign select_ln51_36_fu_975_p3 = ((icmp_ln51_44_fu_969_p2[0:0] == 1'b1) ? trunc_ln44_74_fu_375_p4 : 9'd0);

assign select_ln51_37_fu_989_p3 = ((icmp_ln51_45_fu_983_p2[0:0] == 1'b1) ? trunc_ln44_75_fu_395_p4 : 9'd0);

assign select_ln51_38_fu_1003_p3 = ((icmp_ln51_46_fu_997_p2[0:0] == 1'b1) ? trunc_ln44_76_fu_415_p4 : 9'd0);

assign select_ln51_39_fu_1017_p3 = ((icmp_ln51_47_fu_1011_p2[0:0] == 1'b1) ? trunc_ln44_77_fu_435_p4 : 9'd0);

assign select_ln51_40_fu_1031_p3 = ((icmp_ln51_48_fu_1025_p2[0:0] == 1'b1) ? trunc_ln44_78_fu_455_p4 : 9'd0);

assign select_ln51_41_fu_1045_p3 = ((icmp_ln51_49_fu_1039_p2[0:0] == 1'b1) ? trunc_ln44_79_fu_475_p4 : 9'd0);

assign select_ln51_42_fu_1059_p3 = ((icmp_ln51_50_fu_1053_p2[0:0] == 1'b1) ? trunc_ln44_80_fu_495_p4 : 9'd0);

assign select_ln51_43_fu_1073_p3 = ((icmp_ln51_51_fu_1067_p2[0:0] == 1'b1) ? trunc_ln44_81_fu_515_p4 : 9'd0);

assign select_ln51_44_fu_1087_p3 = ((icmp_ln51_52_fu_1081_p2[0:0] == 1'b1) ? trunc_ln44_82_fu_535_p4 : 9'd0);

assign select_ln51_45_fu_1101_p3 = ((icmp_ln51_53_fu_1095_p2[0:0] == 1'b1) ? trunc_ln44_83_fu_555_p4 : 9'd0);

assign select_ln51_46_fu_1115_p3 = ((icmp_ln51_54_fu_1109_p2[0:0] == 1'b1) ? trunc_ln44_84_fu_575_p4 : 9'd0);

assign select_ln51_47_fu_1129_p3 = ((icmp_ln51_55_fu_1123_p2[0:0] == 1'b1) ? trunc_ln44_85_fu_595_p4 : 9'd0);

assign select_ln51_48_fu_1143_p3 = ((icmp_ln51_56_fu_1137_p2[0:0] == 1'b1) ? trunc_ln44_86_fu_615_p4 : 9'd0);

assign select_ln51_49_fu_1157_p3 = ((icmp_ln51_57_fu_1151_p2[0:0] == 1'b1) ? trunc_ln44_87_fu_635_p4 : 9'd0);

assign select_ln51_50_fu_1171_p3 = ((icmp_ln51_58_fu_1165_p2[0:0] == 1'b1) ? trunc_ln44_88_fu_655_p4 : 9'd0);

assign select_ln51_51_fu_1185_p3 = ((icmp_ln51_59_fu_1179_p2[0:0] == 1'b1) ? trunc_ln44_89_fu_675_p4 : 9'd0);

assign select_ln51_52_fu_1199_p3 = ((icmp_ln51_60_fu_1193_p2[0:0] == 1'b1) ? trunc_ln44_90_fu_695_p4 : 9'd0);

assign select_ln51_53_fu_1213_p3 = ((icmp_ln51_61_fu_1207_p2[0:0] == 1'b1) ? trunc_ln44_91_fu_715_p4 : 9'd0);

assign select_ln51_54_fu_1227_p3 = ((icmp_ln51_62_fu_1221_p2[0:0] == 1'b1) ? trunc_ln44_92_fu_735_p4 : 9'd0);

assign select_ln51_55_fu_1241_p3 = ((icmp_ln51_63_fu_1235_p2[0:0] == 1'b1) ? trunc_ln44_93_fu_755_p4 : 9'd0);

assign select_ln51_56_fu_1255_p3 = ((icmp_ln51_64_fu_1249_p2[0:0] == 1'b1) ? trunc_ln44_94_fu_775_p4 : 9'd0);

assign select_ln51_57_fu_1269_p3 = ((icmp_ln51_65_fu_1263_p2[0:0] == 1'b1) ? trunc_ln44_95_fu_795_p4 : 9'd0);

assign select_ln51_58_fu_1283_p3 = ((icmp_ln51_66_fu_1277_p2[0:0] == 1'b1) ? trunc_ln44_96_fu_815_p4 : 9'd0);

assign select_ln51_59_fu_1297_p3 = ((icmp_ln51_67_fu_1291_p2[0:0] == 1'b1) ? trunc_ln44_97_fu_835_p4 : 9'd0);

assign select_ln51_60_fu_1311_p3 = ((icmp_ln51_68_fu_1305_p2[0:0] == 1'b1) ? trunc_ln44_98_fu_855_p4 : 9'd0);

assign select_ln51_61_fu_1325_p3 = ((icmp_ln51_69_fu_1319_p2[0:0] == 1'b1) ? trunc_ln_fu_875_p4 : 9'd0);

assign select_ln51_fu_947_p3 = ((icmp_ln51_42_fu_941_p2[0:0] == 1'b1) ? trunc_ln44_72_fu_335_p4 : 9'd0);

assign start_out = real_start;

assign trunc_ln44_100_fu_261_p1 = layer10_out_dout[8:0];

assign trunc_ln44_42_fu_325_p4 = {{layer10_out_dout[49:40]}};

assign trunc_ln44_43_fu_345_p4 = {{layer10_out_dout[59:50]}};

assign trunc_ln44_44_fu_365_p4 = {{layer10_out_dout[69:60]}};

assign trunc_ln44_45_fu_385_p4 = {{layer10_out_dout[79:70]}};

assign trunc_ln44_46_fu_405_p4 = {{layer10_out_dout[89:80]}};

assign trunc_ln44_47_fu_425_p4 = {{layer10_out_dout[99:90]}};

assign trunc_ln44_48_fu_445_p4 = {{layer10_out_dout[109:100]}};

assign trunc_ln44_49_fu_465_p4 = {{layer10_out_dout[119:110]}};

assign trunc_ln44_50_fu_485_p4 = {{layer10_out_dout[129:120]}};

assign trunc_ln44_51_fu_505_p4 = {{layer10_out_dout[139:130]}};

assign trunc_ln44_52_fu_525_p4 = {{layer10_out_dout[149:140]}};

assign trunc_ln44_53_fu_545_p4 = {{layer10_out_dout[159:150]}};

assign trunc_ln44_54_fu_565_p4 = {{layer10_out_dout[169:160]}};

assign trunc_ln44_55_fu_585_p4 = {{layer10_out_dout[179:170]}};

assign trunc_ln44_56_fu_605_p4 = {{layer10_out_dout[189:180]}};

assign trunc_ln44_57_fu_625_p4 = {{layer10_out_dout[199:190]}};

assign trunc_ln44_58_fu_645_p4 = {{layer10_out_dout[209:200]}};

assign trunc_ln44_59_fu_665_p4 = {{layer10_out_dout[219:210]}};

assign trunc_ln44_60_fu_685_p4 = {{layer10_out_dout[229:220]}};

assign trunc_ln44_61_fu_705_p4 = {{layer10_out_dout[239:230]}};

assign trunc_ln44_62_fu_725_p4 = {{layer10_out_dout[249:240]}};

assign trunc_ln44_63_fu_745_p4 = {{layer10_out_dout[259:250]}};

assign trunc_ln44_64_fu_765_p4 = {{layer10_out_dout[269:260]}};

assign trunc_ln44_65_fu_785_p4 = {{layer10_out_dout[279:270]}};

assign trunc_ln44_66_fu_805_p4 = {{layer10_out_dout[289:280]}};

assign trunc_ln44_67_fu_825_p4 = {{layer10_out_dout[299:290]}};

assign trunc_ln44_68_fu_845_p4 = {{layer10_out_dout[309:300]}};

assign trunc_ln44_69_fu_865_p4 = {{layer10_out_dout[319:310]}};

assign trunc_ln44_70_fu_295_p4 = {{layer10_out_dout[28:20]}};

assign trunc_ln44_71_fu_315_p4 = {{layer10_out_dout[38:30]}};

assign trunc_ln44_72_fu_335_p4 = {{layer10_out_dout[48:40]}};

assign trunc_ln44_73_fu_355_p4 = {{layer10_out_dout[58:50]}};

assign trunc_ln44_74_fu_375_p4 = {{layer10_out_dout[68:60]}};

assign trunc_ln44_75_fu_395_p4 = {{layer10_out_dout[78:70]}};

assign trunc_ln44_76_fu_415_p4 = {{layer10_out_dout[88:80]}};

assign trunc_ln44_77_fu_435_p4 = {{layer10_out_dout[98:90]}};

assign trunc_ln44_78_fu_455_p4 = {{layer10_out_dout[108:100]}};

assign trunc_ln44_79_fu_475_p4 = {{layer10_out_dout[118:110]}};

assign trunc_ln44_80_fu_495_p4 = {{layer10_out_dout[128:120]}};

assign trunc_ln44_81_fu_515_p4 = {{layer10_out_dout[138:130]}};

assign trunc_ln44_82_fu_535_p4 = {{layer10_out_dout[148:140]}};

assign trunc_ln44_83_fu_555_p4 = {{layer10_out_dout[158:150]}};

assign trunc_ln44_84_fu_575_p4 = {{layer10_out_dout[168:160]}};

assign trunc_ln44_85_fu_595_p4 = {{layer10_out_dout[178:170]}};

assign trunc_ln44_86_fu_615_p4 = {{layer10_out_dout[188:180]}};

assign trunc_ln44_87_fu_635_p4 = {{layer10_out_dout[198:190]}};

assign trunc_ln44_88_fu_655_p4 = {{layer10_out_dout[208:200]}};

assign trunc_ln44_89_fu_675_p4 = {{layer10_out_dout[218:210]}};

assign trunc_ln44_90_fu_695_p4 = {{layer10_out_dout[228:220]}};

assign trunc_ln44_91_fu_715_p4 = {{layer10_out_dout[238:230]}};

assign trunc_ln44_92_fu_735_p4 = {{layer10_out_dout[248:240]}};

assign trunc_ln44_93_fu_755_p4 = {{layer10_out_dout[258:250]}};

assign trunc_ln44_94_fu_775_p4 = {{layer10_out_dout[268:260]}};

assign trunc_ln44_95_fu_795_p4 = {{layer10_out_dout[278:270]}};

assign trunc_ln44_96_fu_815_p4 = {{layer10_out_dout[288:280]}};

assign trunc_ln44_97_fu_835_p4 = {{layer10_out_dout[298:290]}};

assign trunc_ln44_98_fu_855_p4 = {{layer10_out_dout[308:300]}};

assign trunc_ln44_s_fu_275_p4 = {{layer10_out_dout[18:10]}};

assign trunc_ln_fu_875_p4 = {{layer10_out_dout[318:310]}};

assign zext_ln45_4_fu_1353_p1 = out_data_10_reg_1527;

assign zext_ln45_5_fu_1356_p1 = out_data_12_reg_1532;

assign zext_ln45_6_fu_1359_p1 = out_data_13_reg_1537;

assign zext_ln45_fu_1350_p1 = out_data_8_reg_1522;

assign zext_ln51_33_fu_1365_p1 = select_ln51_35_reg_1547;

assign zext_ln51_34_fu_1368_p1 = select_ln51_36_reg_1552;

assign zext_ln51_35_fu_1371_p1 = select_ln51_37_reg_1557;

assign zext_ln51_36_fu_1374_p1 = select_ln51_38_reg_1562;

assign zext_ln51_37_fu_1377_p1 = select_ln51_39_reg_1567;

assign zext_ln51_38_fu_1380_p1 = select_ln51_40_reg_1572;

assign zext_ln51_39_fu_1383_p1 = select_ln51_41_reg_1577;

assign zext_ln51_40_fu_1386_p1 = select_ln51_42_reg_1582;

assign zext_ln51_41_fu_1389_p1 = select_ln51_43_reg_1587;

assign zext_ln51_42_fu_1392_p1 = select_ln51_44_reg_1592;

assign zext_ln51_43_fu_1395_p1 = select_ln51_45_reg_1597;

assign zext_ln51_44_fu_1398_p1 = select_ln51_46_reg_1602;

assign zext_ln51_45_fu_1401_p1 = select_ln51_47_reg_1607;

assign zext_ln51_46_fu_1404_p1 = select_ln51_48_reg_1612;

assign zext_ln51_47_fu_1407_p1 = select_ln51_49_reg_1617;

assign zext_ln51_48_fu_1410_p1 = select_ln51_50_reg_1622;

assign zext_ln51_49_fu_1413_p1 = select_ln51_51_reg_1627;

assign zext_ln51_50_fu_1416_p1 = select_ln51_52_reg_1632;

assign zext_ln51_51_fu_1419_p1 = select_ln51_53_reg_1637;

assign zext_ln51_52_fu_1422_p1 = select_ln51_54_reg_1642;

assign zext_ln51_53_fu_1425_p1 = select_ln51_55_reg_1647;

assign zext_ln51_54_fu_1428_p1 = select_ln51_56_reg_1652;

assign zext_ln51_55_fu_1431_p1 = select_ln51_57_reg_1657;

assign zext_ln51_56_fu_1434_p1 = select_ln51_58_reg_1662;

assign zext_ln51_57_fu_1437_p1 = select_ln51_59_reg_1667;

assign zext_ln51_58_fu_1440_p1 = select_ln51_60_reg_1672;

assign zext_ln51_fu_1362_p1 = select_ln51_reg_1542;

assign zext_ln57_fu_1510_p1 = or_ln57_s_fu_1443_p33;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_s
