// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.247500,HLS_SYN_LAT=70475,HLS_SYN_TPT=26590,HLS_SYN_MEM=193,HLS_SYN_DSP=0,HLS_SYN_FF=45901,HLS_SYN_LUT=73114,HLS_VERSION=2024_1}" *)

module myproject (
        input_1_TDATA,
        layer18_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_1_TVALID,
        input_1_TREADY,
        ap_start,
        layer18_out_TVALID,
        layer18_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [47:0] input_1_TDATA;
output  [79:0] layer18_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_1_TVALID;
output   input_1_TREADY;
input   ap_start;
output   layer18_out_TVALID;
input   layer18_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_start;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_done;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_continue;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_idle;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_ready;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_start_out;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_input_1_TREADY;
wire   [29:0] zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_din;
wire    zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_write;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer20_out_read;
wire   [79:0] conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_write;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_start;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_done;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_continue;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_idle;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_ready;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer2_out_read;
wire   [79:0] relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_write;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_start_out;
wire    relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_ready;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer4_out_read;
wire   [79:0] pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_din;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_write;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_start;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_done;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_continue;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_idle;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_ready;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_start_out;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer5_out_read;
wire   [79:0] zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_din;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_write;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer21_out_read;
wire   [159:0] conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_din;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer6_out_read;
wire   [159:0] relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_start_write;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_start;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_done;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer8_out_read;
wire   [159:0] pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_din;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_write;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_start_out;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_start_write;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_start;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_done;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_continue;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_idle;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_ready;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_start_out;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_start_write;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer9_out_read;
wire   [159:0] zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_din;
wire    zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_write;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer22_out_read;
wire   [319:0] conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_din;
wire    conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer10_out_read;
wire   [319:0] relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_start_write;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_start;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_done;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer12_out_read;
wire   [319:0] pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_din;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_write;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_start_out;
wire    pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_start_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_start_out;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_start_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer13_out_read;
wire   [319:0] dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_din;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_start_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer15_out_read;
wire   [319:0] relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer17_out_read;
wire   [79:0] dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TDATA;
wire    dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TVALID;
wire    layer20_out_full_n;
wire   [29:0] layer20_out_dout;
wire   [11:0] layer20_out_num_data_valid;
wire   [11:0] layer20_out_fifo_cap;
wire    layer20_out_empty_n;
wire    layer2_out_full_n;
wire   [79:0] layer2_out_dout;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer4_out_full_n;
wire   [79:0] layer4_out_dout;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [79:0] layer5_out_dout;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer21_out_full_n;
wire   [79:0] layer21_out_dout;
wire   [9:0] layer21_out_num_data_valid;
wire   [9:0] layer21_out_fifo_cap;
wire    layer21_out_empty_n;
wire    layer6_out_full_n;
wire   [159:0] layer6_out_dout;
wire   [8:0] layer6_out_num_data_valid;
wire   [8:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer8_out_full_n;
wire   [159:0] layer8_out_dout;
wire   [8:0] layer8_out_num_data_valid;
wire   [8:0] layer8_out_fifo_cap;
wire    layer8_out_empty_n;
wire    layer9_out_full_n;
wire   [159:0] layer9_out_dout;
wire   [6:0] layer9_out_num_data_valid;
wire   [6:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire    layer22_out_full_n;
wire   [159:0] layer22_out_dout;
wire   [7:0] layer22_out_num_data_valid;
wire   [7:0] layer22_out_fifo_cap;
wire    layer22_out_empty_n;
wire    layer10_out_full_n;
wire   [319:0] layer10_out_dout;
wire   [6:0] layer10_out_num_data_valid;
wire   [6:0] layer10_out_fifo_cap;
wire    layer10_out_empty_n;
wire    layer12_out_full_n;
wire   [319:0] layer12_out_dout;
wire   [6:0] layer12_out_num_data_valid;
wire   [6:0] layer12_out_fifo_cap;
wire    layer12_out_empty_n;
wire    layer13_out_full_n;
wire   [319:0] layer13_out_dout;
wire   [4:0] layer13_out_num_data_valid;
wire   [4:0] layer13_out_fifo_cap;
wire    layer13_out_empty_n;
wire    layer15_out_full_n;
wire   [319:0] layer15_out_dout;
wire   [1:0] layer15_out_num_data_valid;
wire   [1:0] layer15_out_fifo_cap;
wire    layer15_out_empty_n;
wire    layer17_out_full_n;
wire   [319:0] layer17_out_dout;
wire   [1:0] layer17_out_num_data_valid;
wire   [1:0] layer17_out_fifo_cap;
wire    layer17_out_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_din;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_din;
wire    start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_dout;
wire    start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_din;
wire    start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_dout;
wire    start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_empty_n;

myproject_zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_s zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_start_write),
    .input_1_TDATA(input_1_TDATA),
    .input_1_TVALID(input_1_TVALID),
    .input_1_TREADY(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_input_1_TREADY),
    .layer20_out_din(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_din),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_full_n(layer20_out_full_n),
    .layer20_out_write(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_write)
);

myproject_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_s conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_start_write),
    .layer20_out_dout(layer20_out_dout),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_empty_n(layer20_out_empty_n),
    .layer20_out_read(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer20_out_read),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_write)
);

myproject_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_s relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_full_n),
    .ap_done(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer2_out_read),
    .layer4_out_din(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_write),
    .start_out(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_start_write)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_s pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer4_out_read),
    .layer5_out_din(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_write),
    .start_out(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_start_write)
);

myproject_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_s zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer5_out_read),
    .layer21_out_din(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_din),
    .layer21_out_num_data_valid(layer21_out_num_data_valid),
    .layer21_out_fifo_cap(layer21_out_fifo_cap),
    .layer21_out_full_n(layer21_out_full_n),
    .layer21_out_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_write)
);

myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_s conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_start_write),
    .layer21_out_dout(layer21_out_dout),
    .layer21_out_num_data_valid(layer21_out_num_data_valid),
    .layer21_out_fifo_cap(layer21_out_fifo_cap),
    .layer21_out_empty_n(layer21_out_empty_n),
    .layer21_out_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer21_out_read),
    .layer6_out_din(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_write)
);

myproject_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_s relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer6_out_read),
    .layer8_out_din(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .start_out(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_s pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_ready),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer8_out_read),
    .layer9_out_din(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_write),
    .start_out(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_start_write)
);

myproject_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_s zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_full_n),
    .ap_done(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_ready),
    .start_out(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_start_out),
    .start_write(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_start_write),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer9_out_read),
    .layer22_out_din(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_din),
    .layer22_out_num_data_valid(layer22_out_num_data_valid),
    .layer22_out_fifo_cap(layer22_out_fifo_cap),
    .layer22_out_full_n(layer22_out_full_n),
    .layer22_out_write(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_write)
);

myproject_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_s conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_start_write),
    .layer22_out_dout(layer22_out_dout),
    .layer22_out_num_data_valid(layer22_out_num_data_valid),
    .layer22_out_fifo_cap(layer22_out_fifo_cap),
    .layer22_out_empty_n(layer22_out_empty_n),
    .layer22_out_read(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer22_out_read),
    .layer10_out_din(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_din),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_write)
);

myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_s relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_ready),
    .layer10_out_dout(layer10_out_dout),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_empty_n(layer10_out_empty_n),
    .layer10_out_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer10_out_read),
    .layer12_out_din(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_din),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap),
    .layer12_out_full_n(layer12_out_full_n),
    .layer12_out_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_write),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_s pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_ready),
    .layer12_out_dout(layer12_out_dout),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap),
    .layer12_out_empty_n(layer12_out_empty_n),
    .layer12_out_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer12_out_read),
    .layer13_out_din(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_din),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_write),
    .start_out(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_start_write)
);

myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_s dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_full_n),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_ready),
    .start_out(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_start_out),
    .start_write(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_start_write),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer13_out_read),
    .layer15_out_din(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_din),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_full_n(layer15_out_full_n),
    .layer15_out_write(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_write)
);

myproject_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_s relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_ready),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_start_write),
    .layer15_out_dout(layer15_out_dout),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_empty_n(layer15_out_empty_n),
    .layer15_out_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer15_out_read),
    .layer17_out_din(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_din),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_write)
);

myproject_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_s dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_start),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_ready),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer17_out_read),
    .layer18_out_TDATA(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TDATA),
    .layer18_out_TVALID(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TVALID),
    .layer18_out_TREADY(layer18_out_TREADY)
);

myproject_fifo_w30_d1156_A layer20_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_din),
    .if_full_n(layer20_out_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_layer20_out_write),
    .if_dout(layer20_out_dout),
    .if_num_data_valid(layer20_out_num_data_valid),
    .if_fifo_cap(layer20_out_fifo_cap),
    .if_empty_n(layer20_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer20_out_read)
);

myproject_fifo_w80_d1024_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer2_out_read)
);

myproject_fifo_w80_d1024_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer4_out_read)
);

myproject_fifo_w80_d256_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer5_out_read)
);

myproject_fifo_w80_d324_A layer21_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_din),
    .if_full_n(layer21_out_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_layer21_out_write),
    .if_dout(layer21_out_dout),
    .if_num_data_valid(layer21_out_num_data_valid),
    .if_fifo_cap(layer21_out_fifo_cap),
    .if_empty_n(layer21_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer21_out_read)
);

myproject_fifo_w160_d256_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer6_out_read)
);

myproject_fifo_w160_d256_A layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer8_out_read)
);

myproject_fifo_w160_d64_A layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer9_out_read)
);

myproject_fifo_w160_d100_A layer22_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_din),
    .if_full_n(layer22_out_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_layer22_out_write),
    .if_dout(layer22_out_dout),
    .if_num_data_valid(layer22_out_num_data_valid),
    .if_fifo_cap(layer22_out_fifo_cap),
    .if_empty_n(layer22_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer22_out_read)
);

myproject_fifo_w320_d64_A layer10_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_din),
    .if_full_n(layer10_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_layer10_out_write),
    .if_dout(layer10_out_dout),
    .if_num_data_valid(layer10_out_num_data_valid),
    .if_fifo_cap(layer10_out_fifo_cap),
    .if_empty_n(layer10_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer10_out_read)
);

myproject_fifo_w320_d64_A layer12_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_din),
    .if_full_n(layer12_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_layer12_out_write),
    .if_dout(layer12_out_dout),
    .if_num_data_valid(layer12_out_num_data_valid),
    .if_fifo_cap(layer12_out_fifo_cap),
    .if_empty_n(layer12_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer12_out_read)
);

myproject_fifo_w320_d16_A layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap),
    .if_empty_n(layer13_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer13_out_read)
);

myproject_fifo_w320_d1_S layer15_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_din),
    .if_full_n(layer15_out_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_layer15_out_write),
    .if_dout(layer15_out_dout),
    .if_num_data_valid(layer15_out_num_data_valid),
    .if_fifo_cap(layer15_out_fifo_cap),
    .if_empty_n(layer15_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer15_out_read)
);

myproject_fifo_w320_d1_S layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap),
    .if_empty_n(layer17_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer17_out_read)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0 start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0 start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5b3s start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5b3s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_ready)
);

myproject_start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config2b4t start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config2b4t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0 start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0 start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0 start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_ready)
);

myproject_start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0 start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config1b5t start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config1b5t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12b6t start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12b6t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0 start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17b7t start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17b7t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_ready)
);

assign ap_done = dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_done;

assign ap_idle = (zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_idle & zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_idle & zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_idle & relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_idle & relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_idle & relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_idle & pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_idle & pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_idle & pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_idle & conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_idle & conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_idle 
    & conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_idle);

assign ap_ready = zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_empty_n;

assign conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_empty_n;

assign conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_empty_n;

assign dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_empty_n;

assign dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_empty_n;

assign input_1_TREADY = zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_input_1_TREADY;

assign layer18_out_TDATA = dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TDATA;

assign layer18_out_TVALID = dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_layer18_out_TVALID;

assign pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_empty_n;

assign pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_ap_start = start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_empty_n;

assign pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_ap_start = start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_empty_n;

assign relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_empty_n;

assign relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_empty_n;

assign relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_ap_start = start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_32u_config10_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_8u_config2_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_16u_config6_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_config15_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_5u_config18_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config5_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config9_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_fixed_10_4_5_3_0_32u_config13_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_5_3_0_16u_relu_config8_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config12_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_5_3_0_32u_relu_config17_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_relu_config4_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_din = 1'b1;

assign zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_fixed_3u_array_ap_fixed_10_4_5_3_0_3u_config20_U0_ap_start = ap_start;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_ap_start = start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_10_4_5_3_0_8u_config21_U0_empty_n;

assign zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_ap_start = start_for_zeropad2d_cl_array_array_ap_fixed_10_4_5_3_0_16u_config22_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myproject

